const DISPOSABLE_DOMAINS = new Set([
  'mailinator.com',
  'guerrillamail.com',
  'guerrillamail.de',
  'tempmail.com',
  'throwaway.email',
  'temp-mail.org',
  'fakeinbox.com',
  'sharklasers.com',
  'guerrillamailblock.com',
  'grr.la',
  'dispostable.com',
  'yopmail.com',
  'trashmail.com',
  'maildrop.cc',
  'mailnesia.com',
  'tempinbox.com',
  'burnermail.io',
  'mailcatch.com',
  'tempr.email',
  'discard.email',
  'getnada.com',
  'emailondeck.com',
  'temp-mail.io',
  'mohmal.com',
  'minutemail.com',
  'harakirimail.com',
  'tmail.ws',
  'mailsac.com',
  'inboxbear.com',
  'crazymailing.com',
  'mailnull.com',
  'spamgourmet.com',
  'jetable.org',
  'mytrashmail.com',
  'fakemailgenerator.com',
  'emailfake.com',
  'tempmailaddress.com',
  'tmpmail.net',
  'tmpmail.org',
  '10minutemail.com',
  'guerrillamail.info',
  'mailforspam.com',
])

export function isDisposableEmail(email) {
  if (!email) return false
  const domain = email.split('@')[1]?.toLowerCase()
  return DISPOSABLE_DOMAINS.has(domain)
}
