const BASE = 'https://aiycgmrubisaxknbeaov.supabase.co'
const KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpeWNnbXJ1YmlzYXhrbmJlYW92Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTkwODIwNiwiZXhwIjoyMDkxNDg0MjA2fQ.SgdX0RO_yUp1c6iQswTpVQwS8TTdpCo9aXR2qlMa7TQ'
const headers = { 'apikey': KEY, 'Authorization': `Bearer ${KEY}`, 'Content-Type': 'application/json' }

async function api(path, opts = {}) {
  const res = await fetch(`${BASE}/rest/v1/${path}`, { method: opts.method || 'GET', headers: { ...headers, ...(opts.headers || {}) }, body: opts.body })
  const text = await res.text()
  if (!res.ok) throw new Error(`${res.status}: ${text}`)
  return text ? JSON.parse(text) : null
}

async function getCompanyId(slug) {
  const data = await api(`companies?slug=eq.${slug}&select=id`)
  return data?.[0]?.id
}

async function insertJobs(jobs) {
  const allKeys = new Set()
  jobs.forEach(j => Object.keys(j).forEach(k => allKeys.add(k)))
  const normalized = jobs.map(j => { const o = {}; allKeys.forEach(k => { o[k] = j[k] !== undefined ? j[k] : null }); return o })
  for (let i = 0; i < normalized.length; i += 10) {
    const batch = normalized.slice(i, i + 10)
    try {
      await api('jobs?on_conflict=slug', { method: 'POST', body: JSON.stringify(batch), headers: { 'Prefer': 'return=minimal,resolution=ignore-duplicates' } })
      console.log(`  Inserted batch ${i / 10 + 1} (${batch.length} jobs)`)
    } catch (e) { console.error(`  Batch ${i / 10 + 1} error:`, e.message) }
  }
}

async function main() {
  const posted_by = '7e44dd04-7718-4564-b128-ad3bc1579c8b'
  const deadline = (d) => new Date(Date.now() + d * 86400000).toISOString().split('T')[0]
  const ago = (h) => new Date(Date.now() - h * 3600000).toISOString()

  const slugs = ['google-india','microsoft-india','amazon-india','flipkart','swiggy','razorpay','adobe-india','infosys','meesho','goldman-sachs-india','zomato','phonepe','nykaa','jio-platforms','tata-group','wipro','groww','cred','dunzo','deloitte-india','bosch-india']
  const co = {}
  for (const s of slugs) { co[s] = await getCompanyId(s) }
  console.log('Company IDs loaded')

  console.log('\nInserting INTERNSHIPS...')
  const internJobs = [
    { slug: 'software-engineering-intern-google-bengaluru', title: 'Software Engineering Intern', description: 'Google STEP/SWE internship for pre-final and final year students.\n\n**Duration:** 3 months\n**PPO chance:** 80%\n\nWork on real Google products with dedicated mentorship and tech talks.', summary: 'Google SWE Intern — 3 months, 80K-1L/month. Work on real products. High PPO chance.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['google-india'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 80000, salary_max: 100000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 50, posted_at: ago(24), application_deadline: deadline(25), skills: ['Data Structures','Algorithms','Python','Java','C++','Problem Solving','System Design'], qualifications: ['Pre-final/final year B.Tech/M.Tech in CS'], department: 'Engineering', industry: 'Technology', benefits: ['Free meals','Transport','Mentorship','Pre-placement offer','Swag'], apply_mode: 'external', apply_url: 'https://careers.google.com/students', status: 'active', is_featured: true, is_urgent: true },
    { slug: 'software-development-intern-microsoft-hyderabad', title: 'Software Development Intern', description: 'Work on Azure, Office 365, or AI platform teams at Microsoft Hyderabad.\n\n**Duration:** 2 months\n**PPO chance:** 75%\n\nDedicated mentors and production code contributions.', summary: 'Microsoft SDE Intern — 2 months, 60K-85K/month. Azure/Office 365/AI teams.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['microsoft-india'], posted_by, location_city: 'Hyderabad', location_state: 'Telangana', location_state_code: 'TG', location_country: 'India', location_country_code: 'IN', salary_min: 60000, salary_max: 85000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 40, posted_at: ago(48), application_deadline: deadline(22), skills: ['C#','Python','Data Structures','Algorithms','Cloud Basics','Problem Solving'], qualifications: ['Pre-final/final year B.Tech in CS/IT'], department: 'Engineering', industry: 'Technology', benefits: ['Free meals','Transport','Mentorship','Pre-placement offer'], apply_mode: 'external', apply_url: 'https://careers.microsoft.com/students', status: 'active', is_featured: true, is_urgent: false },
    { slug: 'sde-intern-amazon-bengaluru', title: 'SDE Intern', description: 'Work on Amazon retail, payments, or logistics systems.\n\n**Duration:** 2 months\n**PPO chance:** 70%\n\nOwn projects end-to-end with performance-based PPO.', summary: 'Amazon SDE Intern — 2 months, 60K-80K/month. Retail/payments/logistics.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['amazon-india'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 60000, salary_max: 80000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 60, posted_at: ago(72), application_deadline: deadline(20), skills: ['Java','Python','Data Structures','Algorithms','OOP','Databases','AWS Basics'], qualifications: ['Pre-final year B.Tech in CS/IT'], department: 'Engineering', industry: 'Technology', benefits: ['Free meals','Transport','Mentorship','Pre-placement offer'], apply_mode: 'external', apply_url: 'https://amazon.jobs/students', status: 'active', is_featured: true, is_urgent: false },
    { slug: 'product-design-intern-flipkart-bengaluru', title: 'Product Design Intern', description: 'Design user experiences for Flipkart e-commerce platform serving 500M+ users.\n\n**Duration:** 3 months\n**PPO chance:** 60%', summary: 'Flipkart Design Intern — 3 months, 40K-60K/month. UX for 500M+ users.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['flipkart'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 40000, salary_max: 60000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 10, posted_at: ago(24), application_deadline: deadline(18), skills: ['Figma','UI/UX Design','User Research','Wireframing','Prototyping','Design Thinking'], qualifications: ['Design students or fresh graduates with portfolio'], department: 'Design', industry: 'E-commerce', benefits: ['Free meals','Mentorship','Conversion to full-time'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'data-science-intern-swiggy-bengaluru', title: 'Data Science Intern', description: 'Work on data-driven problems in food delivery logistics.\n\n**Duration:** 4 months\n**PPO chance:** 65%\n\nApply ML models to optimize delivery routes and predict demand.', summary: 'Swiggy Data Science Intern — 4 months, 30K-50K/month. ML for logistics.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['swiggy'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 30000, salary_max: 50000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 8, posted_at: ago(48), application_deadline: deadline(22), skills: ['Python','SQL','Machine Learning','Pandas','Statistics','Data Visualization','EDA'], qualifications: ['Final year B.Tech/M.Tech or post-graduate in CS/Stats'], department: 'Data Science', industry: 'Food Tech', benefits: ['Free Swiggy credits','Mentorship','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'backend-development-intern-razorpay-bengaluru', title: 'Backend Development Intern', description: 'Build and test microservices for Razorpay payment infrastructure.\n\n**Duration:** 3 months\n**PPO chance:** 60%', summary: 'Razorpay Backend Intern — 3 months, 25K-45K/month. Payments at scale.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['razorpay'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 25000, salary_max: 45000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 12, posted_at: ago(96), application_deadline: deadline(24), skills: ['Go','Java','Python','REST APIs','SQL','Git','Docker Basics'], qualifications: ['Pre-final/final year B.Tech in CS/IT'], department: 'Engineering', industry: 'Fintech', benefits: ['Mentorship','Free meals','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'ai-ml-research-intern-adobe-noida', title: 'AI/ML Research Intern', description: 'Conduct AI research at Adobe India Research Lab.\n\n**Duration:** 6 months\n**PPO chance:** 70%\n\nWork on generative models, CV, and NLP. Co-author papers at top conferences.', summary: 'Adobe AI Research Intern — 6 months, 80K-1L/month. GenAI, CV, NLP. Publish at top venues.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['adobe-india'], posted_by, location_city: 'Noida', location_state: 'Uttar Pradesh', location_state_code: 'UP', location_country: 'India', location_country_code: 'IN', salary_min: 80000, salary_max: 100000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 15, posted_at: ago(120), application_deadline: deadline(20), skills: ['Python','Deep Learning','PyTorch','TensorFlow','Computer Vision','NLP','Research Papers'], qualifications: ['M.Tech/PhD students in CS/AI/ML'], department: 'Research', industry: 'Technology', benefits: ['Research mentorship','Conference travel','Publication support','PPO'], apply_mode: 'external', apply_url: 'https://research.adobe.com/careers', status: 'active', is_featured: true, is_urgent: false },
    { slug: 'full-stack-intern-infosys-instep-bengaluru', title: 'Full Stack Development Intern — InStep', description: 'Infosys InStep global internship program.\n\n**Duration:** 3 months\n**PPO chance:** 50%\n\nHands-on enterprise application development.', summary: 'Infosys InStep Intern — 3 months, 25K-50K/month. Enterprise full-stack.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['infosys'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 25000, salary_max: 50000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 30, posted_at: ago(72), application_deadline: deadline(28), skills: ['React','Node.js','JavaScript','HTML/CSS','MongoDB','Git','REST APIs','Agile'], qualifications: ['Pre-final/final year B.Tech in CS/IT'], department: 'Engineering', industry: 'IT Services', benefits: ['Certificate','Mentorship','Campus housing','Pre-placement offer'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'marketing-intern-meesho-bengaluru', title: 'Marketing Intern', description: 'Support Meesho growth marketing team.\n\n**Duration:** 3 months\n**PPO chance:** 40%\n\nGrowth hacking for a hyper-growth social commerce startup.', summary: 'Meesho Marketing Intern — 3 months, 15K-25K/month. Growth marketing, social media.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['meesho'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 15000, salary_max: 25000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 8, posted_at: ago(24), application_deadline: deadline(20), skills: ['Digital Marketing','Social Media','Content Creation','Analytics','Canva','SEO Basics'], qualifications: ['Any year student — marketing or communications preferred'], department: 'Marketing', industry: 'E-commerce', benefits: ['Certificate','Mentorship','Flexible hours','Meesho credits'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'finance-intern-goldman-sachs-bengaluru', title: 'Finance Intern — Summer Analyst', description: 'Summer analyst internship at Goldman Sachs.\n\n**Duration:** 2 months\n**PPO chance:** 85%\n\nWork on live deals, market analysis, and risk assessment.', summary: 'Goldman Sachs Summer Analyst — 2 months, 50K-75K/month. Live deals, market analysis.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['goldman-sachs-india'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 50000, salary_max: 75000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 20, posted_at: ago(144), application_deadline: deadline(18), skills: ['Financial Analysis','Excel','Accounting','Valuation','Financial Modeling','Communication'], qualifications: ['Pre-final year MBA/finance/CA students'], department: 'Investment Banking', industry: 'BFSI', benefits: ['Top-tier compensation','Mentorship','Networking events','PPO'], apply_mode: 'external', apply_url: 'https://goldmansachs.com/careers', status: 'active', is_featured: true, is_urgent: false },
    { slug: 'content-writing-intern-zomato-remote', title: 'Content Writing Intern', description: 'Create engaging food and restaurant content for Zomato.\n\n**Duration:** 3 months\n**PPO chance:** 30%\n\nWrite restaurant reviews, city food guides. Fully remote.', summary: 'Zomato Content Intern — 3 months, 10K-20K/month. Food writing, SEO content. Remote.', category: 'internship', job_type: 'internship', work_mode: 'remote', company_id: co['zomato'], posted_by, location_country: 'India', location_country_code: 'IN', salary_min: 10000, salary_max: 20000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 15, posted_at: ago(48), application_deadline: deadline(25), skills: ['Creative Writing','SEO Writing','Social Media','Research','Grammar','Content Strategy'], qualifications: ['Any year student — English/journalism preferred'], department: 'Content', industry: 'Food Tech', benefits: ['Remote work','Zomato credits','Certificate','Portfolio building'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'devops-intern-phonepe-bengaluru', title: 'DevOps Intern', description: 'Learn DevOps practices for PhonePe infrastructure.\n\n**Duration:** 4 months\n**PPO chance:** 55%\n\nCloud infrastructure, monitoring, deployment automation at scale.', summary: 'PhonePe DevOps Intern — 4 months, 25K-40K/month. Cloud, CI/CD at scale.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['phonepe'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 25000, salary_max: 40000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 6, posted_at: ago(96), application_deadline: deadline(22), skills: ['Linux','Docker','AWS','Python','CI/CD','Git','Networking Basics'], qualifications: ['Pre-final/final year B.Tech in CS/IT'], department: 'Platform Engineering', industry: 'Fintech', benefits: ['Mentorship','Free meals','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'graphic-design-intern-nykaa-mumbai', title: 'Graphic Design Intern', description: 'Create visual content for Nykaa beauty and fashion brand.\n\n**Duration:** 3 months\n**PPO chance:** 35%', summary: 'Nykaa Design Intern — 3 months, 10K-18K/month. Beauty brand visuals.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['nykaa'], posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 10000, salary_max: 18000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 5, posted_at: ago(24), application_deadline: deadline(20), skills: ['Adobe Photoshop','Illustrator','Canva','Social Media Design','Typography','Color Theory'], qualifications: ['Design students — any year'], department: 'Creative', industry: 'E-commerce', benefits: ['Nykaa products','Certificate','Portfolio building'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'machine-learning-intern-jio-hyderabad', title: 'Machine Learning Intern', description: 'Work on ML projects for Jio telecom and digital services.\n\n**Duration:** 6 months\n**PPO chance:** 50%', summary: 'Jio ML Intern — 6 months, 20K-35K/month. Telecom ML, network optimization.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['jio-platforms'], posted_by, location_city: 'Hyderabad', location_state: 'Telangana', location_state_code: 'TG', location_country: 'India', location_country_code: 'IN', salary_min: 20000, salary_max: 35000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 10, posted_at: ago(120), application_deadline: deadline(25), skills: ['Python','TensorFlow','PyTorch','Machine Learning','NLP','NumPy','Pandas'], qualifications: ['M.Tech/final year B.Tech in CS/AI/ML'], department: 'AI Centre', industry: 'Telecom', benefits: ['Mentorship','Certificate','Jio benefits','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'hr-intern-tata-group-mumbai', title: 'HR Intern', description: 'Support HR team with recruitment and employee engagement.\n\n**Duration:** 2 months\n**PPO chance:** 40%', summary: 'Tata Group HR Intern — 2 months, 12K-20K/month. Recruitment, onboarding.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['tata-group'], posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 12000, salary_max: 20000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 10, posted_at: ago(72), application_deadline: deadline(22), skills: ['HR Basics','Communication','Excel','Recruitment','Employee Engagement'], qualifications: ['MBA HR students — any year'], department: 'Human Resources', industry: 'Conglomerate', benefits: ['Certificate','Tata brand on CV','Mentorship'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'cybersecurity-intern-wipro-hyderabad', title: 'Cybersecurity Intern', description: 'Assist cybersecurity team with threat monitoring and security audits.\n\n**Duration:** 3 months\n**PPO chance:** 45%', summary: 'Wipro Cybersecurity Intern — 3 months, 15K-25K/month. Threat monitoring.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['wipro'], posted_by, location_city: 'Hyderabad', location_state: 'Telangana', location_state_code: 'TG', location_country: 'India', location_country_code: 'IN', salary_min: 15000, salary_max: 25000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 8, posted_at: ago(48), application_deadline: deadline(24), skills: ['Network Security','SIEM Basics','Linux','Python','Vulnerability Assessment','OWASP'], qualifications: ['CS/IT students — pre-final/final year'], department: 'Cybersecurity', industry: 'IT Services', benefits: ['Certificate','Training','Mentorship','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'business-development-intern-groww-bengaluru', title: 'Business Development Intern', description: 'Drive user acquisition and partnership initiatives for Groww.\n\n**Duration:** 3 months\n**PPO chance:** 40%', summary: 'Groww BD Intern — 3 months, 15K-25K/month. Fintech partnerships.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['groww'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 15000, salary_max: 25000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 6, posted_at: ago(24), application_deadline: deadline(20), skills: ['Communication','Sales','Market Research','Excel','CRM Tools','Presentation'], qualifications: ['MBA/BBA students — any year'], department: 'Business Development', industry: 'Fintech', benefits: ['Certificate','Groww credits','Mentorship'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'frontend-development-intern-cred-bengaluru', title: 'Frontend Development Intern', description: 'Build beautiful UI components for CRED fintech app.\n\n**Duration:** 3 months\n**PPO chance:** 60%\n\nDesign-first engineering culture.', summary: 'CRED Frontend Intern — 3 months, 30K-50K/month. Premium fintech UI, React.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['cred'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 30000, salary_max: 50000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 8, posted_at: ago(48), application_deadline: deadline(18), skills: ['React','JavaScript','TypeScript','HTML/CSS','Git','Responsive Design','API Integration'], qualifications: ['Pre-final/final year B.Tech in CS/IT'], department: 'Frontend Engineering', industry: 'Fintech', benefits: ['Free meals','Mentorship','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: true },
    { slug: 'supply-chain-operations-intern-amazon-delhi', title: 'Supply Chain & Operations Intern', description: 'Support Amazon fulfilment centre operations.\n\n**Duration:** 2 months\n**PPO chance:** 65%\n\nProcess improvement and logistics optimization at massive scale.', summary: 'Amazon Ops Intern — 2 months, 20K-35K/month. Fulfilment centre, supply chain.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['amazon-india'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 20000, salary_max: 35000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 15, posted_at: ago(96), application_deadline: deadline(22), skills: ['Excel','Data Analysis','Supply Chain Basics','Communication','Problem Solving','SQL Basics'], qualifications: ['MBA/engineering students — any year'], department: 'Operations', industry: 'E-commerce', benefits: ['Certificate','Amazon credits','Mentorship','PPO consideration'], apply_mode: 'external', apply_url: 'https://amazon.jobs/students', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'social-media-marketing-intern-dunzo-remote', title: 'Social Media Marketing Intern', description: 'Manage social media presence and create content for Dunzo.\n\n**Duration:** 3 months\n**PPO chance:** 25%\n\nCreate memes/reels, track engagement. Fully remote.', summary: 'Dunzo Social Media Intern — 3 months, 8K-15K/month. Content creation. Remote.', category: 'internship', job_type: 'internship', work_mode: 'remote', company_id: co['dunzo'], posted_by, location_country: 'India', location_country_code: 'IN', salary_min: 8000, salary_max: 15000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 5, posted_at: ago(24), application_deadline: deadline(18), skills: ['Social Media Management','Content Creation','Instagram','Twitter','Analytics','Canva'], qualifications: ['Any year student — marketing/communications preferred'], department: 'Marketing', industry: 'Quick Commerce', benefits: ['Remote work','Certificate','Dunzo credits'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'data-analytics-intern-deloitte-mumbai', title: 'Data Analytics Intern', description: 'Work on consulting analytics projects for enterprise clients.\n\n**Duration:** 3 months\n**PPO chance:** 60%\n\nBuild dashboards and present insights to stakeholders.', summary: 'Deloitte Analytics Intern — 3 months, 25K-40K/month. Consulting analytics, Power BI.', category: 'internship', job_type: 'internship', work_mode: 'hybrid', company_id: co['deloitte-india'], posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 25000, salary_max: 40000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 12, posted_at: ago(120), application_deadline: deadline(20), skills: ['SQL','Python','Excel','Power BI','Tableau','Statistics','Data Cleaning'], qualifications: ['Final year B.Tech/MBA/M.Sc in analytics/stats'], department: 'Consulting', industry: 'Consulting', benefits: ['Certificate','Deloitte brand on CV','Mentorship','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'embedded-systems-intern-bosch-bengaluru', title: 'Embedded Systems Intern', description: 'Work on automotive and IoT embedded systems at Bosch R&D.\n\n**Duration:** 6 months\n**PPO chance:** 55%\n\nReal-time systems, sensor integration, automotive-grade software.', summary: 'Bosch Embedded Intern — 6 months, 20K-35K/month. Automotive IoT, RTOS.', category: 'internship', job_type: 'internship', work_mode: 'onsite', company_id: co['bosch-india'], posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 20000, salary_max: 35000, salary_currency: 'INR', salary_period: 'month', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 10, posted_at: ago(72), application_deadline: deadline(25), skills: ['C/C++','Embedded C','Microcontrollers','RTOS','IoT','PCB Design','Serial Protocols'], qualifications: ['ECE/EEE final year B.Tech students'], department: 'R&D', industry: 'Manufacturing', benefits: ['Certificate','Bosch brand on CV','Mentorship','PPO consideration'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
  ]
  await insertJobs(internJobs)
  console.log('Internships done!')
}

main().catch(console.error)
