const BASE = 'https://aiycgmrubisaxknbeaov.supabase.co'
const KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpeWNnbXJ1YmlzYXhrbmJlYW92Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTkwODIwNiwiZXhwIjoyMDkxNDg0MjA2fQ.SgdX0RO_yUp1c6iQswTpVQwS8TTdpCo9aXR2qlMa7TQ'
const headers = { 'apikey': KEY, 'Authorization': `Bearer ${KEY}`, 'Content-Type': 'application/json', 'Prefer': 'return=representation' }

async function api(path, opts = {}) {
  const mergedHeaders = { ...headers, ...(opts.headers || {}) }
  const res = await fetch(`${BASE}/rest/v1/${path}`, { method: opts.method || 'GET', headers: mergedHeaders, body: opts.body })
  const text = await res.text()
  if (!res.ok) throw new Error(`${res.status}: ${text}`)
  return text ? JSON.parse(text) : null
}

async function getCompanyId(slug) {
  const data = await api(`companies?slug=eq.${slug}&select=id`)
  return data?.[0]?.id
}

async function insertJobs(jobs) {
  const allKeys = new Set()
  jobs.forEach(j => Object.keys(j).forEach(k => allKeys.add(k)))
  const normalized = jobs.map(j => {
    const obj = {}
    allKeys.forEach(k => { obj[k] = j[k] !== undefined ? j[k] : null })
    return obj
  })
  for (let i = 0; i < normalized.length; i += 10) {
    const batch = normalized.slice(i, i + 10)
    try {
      await api('jobs?on_conflict=slug', { method: 'POST', body: JSON.stringify(batch), headers: { 'Prefer': 'return=minimal,resolution=ignore-duplicates' } })
      console.log(`  Inserted batch ${i / 10 + 1} (${batch.length} jobs)`)
    } catch (e) { console.error(`  Batch ${i / 10 + 1} error:`, e.message) }
  }
}

async function main() {
  const posted_by = '7e44dd04-7718-4564-b128-ad3bc1579c8b'
  const deadline = (days) => new Date(Date.now() + days * 86400000).toISOString().split('T')[0]
  const ago = (hours) => new Date(Date.now() - hours * 3600000).toISOString()

  // Get company IDs
  const slugs = ['ssc','ibps','state-bank-of-india','rbi','rrb','drdo','indian-army','indian-navy','indian-air-force','kvs','nvs','ntpc','ongc','iocl','bhel','state-psc','cbse']
  const co = {}
  for (const s of slugs) {
    co[s] = await getCompanyId(s)
    if (!co[s]) console.warn(`  Company not found: ${s}`)
  }
  console.log('Company IDs loaded')

  console.log('\nInserting GOVERNMENT jobs...')
  const govJobs = [
    { slug: 'ssc-cgl-2026-combined-graduate-level', title: 'SSC CGL 2026 — Combined Graduate Level', description: 'Staff Selection Commission Combined Graduate Level Examination 2026.\n\n12,256 vacancies across central government ministries.\nPosts include Tax Assistant, Auditor, Inspector, Sub-Inspector, and Section Officer.\n\nTier 1 exam: August-September 2026.\nTier 2 exam: November 2026.', summary: 'SSC CGL 2026 — 12,256 vacancies. Tax Assistant, Auditor, Inspector, Section Officer posts.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['ssc'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 420000, salary_max: 900000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 12256, posted_at: ago(24), application_deadline: deadline(30), skills: ['Quantitative Aptitude','Reasoning','English','General Awareness','Computer Proficiency'], qualifications: ['Bachelor degree from recognized university'], department: 'Multiple Ministries', industry: 'Government', benefits: ['Pension','DA','HRA','Medical','LTC'], apply_mode: 'external', apply_url: 'https://ssc.gov.in', government_meta: {organization:'SSC',notification_number:'SSC/CGL/2026',exam_date:'2026-08-20',age_min:18,age_max:32,age_relaxation:'OBC +3, SC/ST +5',fee_general:100,fee_reserved:0,vacancies:12256}, status: 'active', is_featured: true, is_urgent: true, faq: [{q:'What is the eligibility for SSC CGL?',a:'Bachelor degree from a recognized university. Age 18-32 years.'},{q:'What is the exam pattern?',a:'Tier 1 (objective MCQ), Tier 2 (descriptive + MCQ), followed by document verification.'}] },
    { slug: 'ssc-chsl-2026-higher-secondary-level', title: 'SSC CHSL 2026 — Combined Higher Secondary Level', description: 'SSC CHSL Examination 2026 for LDC, Junior Secretariat Assistant, Data Entry Operator, and Postal Assistant posts.\n\n3,500+ vacancies across central government offices.\n12th pass eligible.', summary: 'SSC CHSL 2026 — 3,500+ vacancies. LDC, JSA, DEO, Postal Assistant posts. 12th pass eligible.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['ssc'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 252000, salary_max: 540000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 3500, posted_at: ago(72), application_deadline: deadline(35), skills: ['English','Quantitative Aptitude','Reasoning','General Awareness','Typing Speed'], qualifications: ['Class 12 pass from recognized board'], department: 'Multiple Ministries', industry: 'Government', benefits: ['Pension','DA','HRA','Medical'], apply_mode: 'external', apply_url: 'https://ssc.gov.in', government_meta: {organization:'SSC',notification_number:'SSC/CHSL/2026',exam_date:'2026-09-15',age_min:18,age_max:27,age_relaxation:'OBC +3, SC/ST +5',fee_general:100,fee_reserved:0,vacancies:3500}, status: 'active', is_featured: true, is_urgent: false },
    { slug: 'ibps-po-2026-probationary-officer', title: 'IBPS PO 2026 — Probationary Officer', description: 'IBPS PO/MT recruitment 2026 for 6,715 vacancies across participating public sector banks.\n\n29% increase in vacancies from last year.\nPrelims: August 2026. Mains: October 2026.', summary: 'IBPS PO 2026 — 6,715 vacancies (29% increase). Bank Probationary Officer across PSU banks.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['ibps'], posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 528000, salary_max: 1080000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 6715, posted_at: ago(48), application_deadline: deadline(28), skills: ['Quantitative Aptitude','Reasoning','English','Banking Awareness','Computer Knowledge'], qualifications: ['Bachelor degree in any discipline'], department: 'Banking Operations', industry: 'Government / BFSI', benefits: ['DA','HRA','Pension','Medical','Leased accommodation'], apply_mode: 'external', apply_url: 'https://ibps.in', government_meta: {organization:'IBPS',notification_number:'IBPS/CRP-PO/MT-XVI',exam_date:'2026-08-15',age_min:20,age_max:30,age_relaxation:'OBC +3, SC/ST +5',fee_general:850,fee_reserved:175,vacancies:6715}, status: 'active', is_featured: true, is_urgent: true, faq: [{q:'Which banks participate in IBPS PO?',a:'All nationalized banks except SBI — PNB, BOB, Canara Bank, Union Bank, Indian Bank, etc.'},{q:'What is the starting salary?',a:'Approx 44,000/month basic + DA, HRA, and other allowances.'}] },
    { slug: 'sbi-clerk-junior-associate-2026', title: 'SBI Clerk 2026 — Junior Associate', description: 'SBI Junior Associate (Clerk) recruitment 2026.\n\nApprox 10,000-12,000 vacancies at SBI branches nationwide.\nPrelims + Mains + Local Language Test.', summary: 'SBI Clerk 2026 — 10,000+ vacancies. Junior Associate at SBI branches nationwide.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['state-bank-of-india'], posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 336000, salary_max: 660000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 10000, posted_at: ago(24), application_deadline: deadline(25), skills: ['Numerical Ability','Reasoning','English','General Awareness','Computer Skills'], qualifications: ['Bachelor degree in any discipline'], department: 'Retail Banking', industry: 'Government / BFSI', benefits: ['DA','HRA','Pension','Medical','Staff loan at concessional rates'], apply_mode: 'external', apply_url: 'https://sbi.co.in/careers', government_meta: {organization:'SBI',notification_number:'CRPD/CR/2026',exam_date:'2026-09-05',age_min:20,age_max:28,age_relaxation:'OBC +3, SC/ST +5',fee_general:750,fee_reserved:125,vacancies:10000}, status: 'active', is_featured: true, is_urgent: false },
    { slug: 'rbi-grade-b-officer-2026', title: 'RBI Grade B Officer 2026', description: 'Reserve Bank of India Grade B (DR) Officer recruitment 2026.\n\nPrestigious officer-grade position at India central bank.\nPhase I + Phase II + Interview.', summary: 'RBI Grade B 2026 — Officer at India central bank. Monetary policy, banking supervision.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['rbi'], posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 780000, salary_max: 1500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 300, posted_at: ago(96), application_deadline: deadline(22), skills: ['Economics','Finance','Quantitative Aptitude','English','Banking Regulation','Reasoning'], qualifications: ['Bachelor degree with 60% or equivalent CGPA'], department: 'Banking Regulation', industry: 'Government / BFSI', benefits: ['Pension','Quarters','Medical','DA','Car loan'], apply_mode: 'external', apply_url: 'https://rbi.org.in/careers', government_meta: {organization:'RBI',notification_number:'RBI/DR/2026',exam_date:'2026-09-20',age_min:21,age_max:30,age_relaxation:'OBC +3, SC/ST +5',fee_general:850,fee_reserved:100,vacancies:300}, status: 'active', is_featured: true, is_urgent: false },
    { slug: 'rrb-ntpc-graduate-level-2026', title: 'RRB NTPC 2026 — Graduate Level', description: 'Railway Recruitment Board NTPC graduate-level recruitment 2026.\n\n5,810 vacancies for Station Master, Traffic Assistant, Goods Guard, Senior Clerk.', summary: 'RRB NTPC 2026 — 5,810 vacancies. Station Master, Traffic Assistant, Goods Guard posts.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['rrb'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 360000, salary_max: 780000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 5810, posted_at: ago(120), application_deadline: deadline(30), skills: ['Mathematics','Reasoning','General Awareness','General Science','English'], qualifications: ['Bachelor degree from recognized university'], department: 'Railways', industry: 'Government', benefits: ['Pension','DA','HRA','Medical','Free rail travel'], apply_mode: 'external', apply_url: 'https://rrbcdg.gov.in', government_meta: {organization:'RRB',notification_number:'RRB/NTPC/2026',exam_date:'2026-10-10',age_min:18,age_max:33,age_relaxation:'OBC +3, SC/ST +5',fee_general:500,fee_reserved:250,vacancies:5810}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'rrb-group-d-level1-2026', title: 'Railway Group D 2026 — Level 1 Posts', description: 'RRB recruitment for Track Maintainer, Helper, Porter, and other Level-1 posts.\n\n30,000 vacancies across Indian Railways. 10th pass + ITI eligible.', summary: 'Railway Group D 2026 — 30,000 vacancies. Track Maintainer, Helper, Porter. 10th pass eligible.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['rrb'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 216000, salary_max: 420000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 30000, posted_at: ago(72), application_deadline: deadline(35), skills: ['Mathematics','Reasoning','General Science','General Awareness','Physical Fitness'], qualifications: ['10th pass + ITI or equivalent'], department: 'Railways', industry: 'Government', benefits: ['Pension','DA','Medical','Free rail travel','Quarters'], apply_mode: 'external', apply_url: 'https://rrbcdg.gov.in', government_meta: {organization:'RRB',notification_number:'RRB/GD/2026',exam_date:'2026-11-01',age_min:18,age_max:33,age_relaxation:'OBC +3, SC/ST +5',fee_general:500,fee_reserved:250,vacancies:30000}, status: 'active', is_featured: true, is_urgent: true },
    { slug: 'rrb-alp-assistant-loco-pilot-2026', title: 'RRB ALP 2026 — Assistant Loco Pilot', description: 'Recruitment for Assistant Loco Pilot and Technician posts in Indian Railways.\n\nProgression to Loco Pilot. ITI/Diploma eligible.', summary: 'RRB ALP 2026 — Assistant Loco Pilot. Technical posts in Indian Railways.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['rrb'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 300000, salary_max: 660000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 5000, posted_at: ago(48), application_deadline: deadline(28), skills: ['Physics','Mathematics','Technical Knowledge','Electrical Basics','Mechanical Aptitude'], qualifications: ['10th + ITI or Diploma in Engineering'], department: 'Railways — Loco', industry: 'Government', benefits: ['Pension','DA','Running allowance','Medical','Free rail travel'], apply_mode: 'external', apply_url: 'https://rrbcdg.gov.in', government_meta: {organization:'RRB',notification_number:'RRB/ALP/2026',exam_date:'2026-10-25',age_min:18,age_max:30,age_relaxation:'OBC +3, SC/ST +5',fee_general:500,fee_reserved:250,vacancies:5000}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'drdo-scientist-b-2026', title: 'DRDO Scientist B 2026', description: 'Entry-level scientist positions at India premier defence research organization.\n\nWork on missiles, radar, electronic warfare, advanced materials.\nRecruitment through GATE score.', summary: 'DRDO Scientist B 2026 — Defence research. Missiles, radar, electronic warfare. GATE-based.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['drdo'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 560000, salary_max: 1200000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 400, posted_at: ago(144), application_deadline: deadline(20), skills: ['Engineering','Research Methodology','GATE Score','Technical Writing','Problem Solving'], qualifications: ['B.E./B.Tech with valid GATE score in ECE/ME/CS/EE'], department: 'Defence R&D', industry: 'Government / Defence', benefits: ['Pension','Quarters','Medical','DA','Professional allowance'], apply_mode: 'external', apply_url: 'https://drdo.gov.in/careers', government_meta: {organization:'DRDO',notification_number:'DRDO/RAC/2026',exam_date:'2026-09-01',age_min:18,age_max:28,age_relaxation:'OBC +3, SC/ST +5',fee_general:100,fee_reserved:0,vacancies:400}, status: 'active', is_featured: true, is_urgent: false },
    { slug: 'indian-army-cds-officer-entry-2026', title: 'Indian Army Officer — CDS Entry 2026', description: 'Combined Defence Services examination for officer entry into Indian Army, Navy, Air Force, and OTA.\n\nTraining at IMA Dehradun / OTA Chennai.\nUPSC written exam + SSB interview.', summary: 'CDS 2026 — Officer entry into Army, Navy, Air Force. UPSC exam + SSB interview.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['indian-army'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 560000, salary_max: 1400000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 450, posted_at: ago(96), application_deadline: deadline(25), skills: ['Physical Fitness','Leadership','General Knowledge','English','Mathematics','Strategic Thinking'], qualifications: ['Bachelor degree for IMA/Naval/AFA, any graduate for OTA'], department: 'Defence — Officer', industry: 'Government / Defence', benefits: ['Pension','Quarters','Medical','Canteen','Travel allowance'], apply_mode: 'external', apply_url: 'https://upsconline.gov.in', government_meta: {organization:'UPSC (CDS)',notification_number:'UPSC/CDS-II/2026',exam_date:'2026-09-07',age_min:20,age_max:25,fee_general:200,fee_reserved:0,vacancies:450}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'indian-navy-ssr-sailor-2026', title: 'Indian Navy SSR 2026 — Sailor', description: 'Recruitment for Senior Secondary Recruit sailors in the Indian Navy.\n\nTraining at INS Chilka. 12th with PCM required.', summary: 'Navy SSR 2026 — Sailor recruitment. Training at INS Chilka. 12th PCM eligible.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['indian-navy'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 252000, salary_max: 540000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 2500, posted_at: ago(120), application_deadline: deadline(30), skills: ['Physics','Mathematics','English','Physical Fitness','Swimming','Technical Aptitude'], qualifications: ['12th pass with Physics, Chemistry, and Mathematics'], department: 'Navy — Sailor', industry: 'Government / Defence', benefits: ['Pension','Free rations','Medical','Canteen','Travel'], apply_mode: 'external', apply_url: 'https://joinindiannavy.gov.in', government_meta: {organization:'Indian Navy',notification_number:'Navy/SSR/2026',age_min:17,age_max:20,fee_general:0,fee_reserved:0,vacancies:2500}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'iaf-agniveer-2026', title: 'Indian Air Force Agniveer 2026', description: 'Recruitment under the Agniveer scheme for 4-year tenure in IAF.\n\nTechnical and non-technical trades. 25% retained as permanent cadre.', summary: 'IAF Agniveer 2026 — 4-year tenure. Technical and non-technical trades. 12th pass eligible.', category: 'government', job_type: 'contract', work_mode: 'onsite', company_id: co['indian-air-force'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 252000, salary_max: 480000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 3500, posted_at: ago(24), application_deadline: deadline(28), skills: ['Physics','Mathematics','English','Physical Fitness','Reasoning','Technical Aptitude'], qualifications: ['12th pass with Physics and Mathematics'], department: 'Air Force — Agniveer', industry: 'Government / Defence', benefits: ['Seva Nidhi','Risk allowance','Ration','Medical'], apply_mode: 'external', apply_url: 'https://indianairforce.nic.in', government_meta: {organization:'Indian Air Force',notification_number:'IAF/AGV/2026',age_min:17,age_max:21,fee_general:0,fee_reserved:0,vacancies:3500}, status: 'active', is_featured: false, is_urgent: true },
    { slug: 'kvs-tgt-trained-graduate-teacher-2026', title: 'KVS TGT 2026 — Trained Graduate Teacher', description: 'Kendriya Vidyalaya Sangathan TGT recruitment 2026.\n\n3,069 vacancies across KVS schools nationwide.\nSubjects: English, Hindi, Mathematics, Science, Social Studies.', summary: 'KVS TGT 2026 — 3,069 vacancies. Teaching in Kendriya Vidyalaya schools. CTET required.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['kvs'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 444000, salary_max: 1140000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 3069, posted_at: ago(72), application_deadline: deadline(22), skills: ['Subject Expertise','Pedagogy','CTET','Classroom Management','Communication'], qualifications: ['Bachelor degree with B.Ed + CTET Paper-II'], department: 'Education', industry: 'Government / Education', benefits: ['Pension','DA','HRA','Medical','Transfer across India'], apply_mode: 'external', apply_url: 'https://kvsangathan.nic.in', government_meta: {organization:'KVS',notification_number:'KVS/TGT/2026',exam_date:'2026-10-15',age_min:21,age_max:35,age_relaxation:'OBC +3, SC/ST +5',fee_general:1500,fee_reserved:0,vacancies:3069}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'kvs-prt-primary-teacher-2026', title: 'KVS PRT 2026 — Primary Teacher', description: 'KVS Primary Teacher recruitment 2026.\n\n3,630 vacancies for Classes I-V across 1,250+ Kendriya Vidyalaya schools.', summary: 'KVS PRT 2026 — 3,630 vacancies. Primary teacher in KV schools. CTET Paper-I required.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['kvs'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 396000, salary_max: 960000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 3630, posted_at: ago(72), application_deadline: deadline(22), skills: ['Primary Education','Child Psychology','CTET Paper-I','Activity-Based Learning','Communication'], qualifications: ['Graduate with D.El.Ed or B.Ed + CTET Paper-I'], department: 'Education', industry: 'Government / Education', benefits: ['Pension','DA','HRA','Medical','Transfer across India'], apply_mode: 'external', apply_url: 'https://kvsangathan.nic.in', government_meta: {organization:'KVS',notification_number:'KVS/PRT/2026',exam_date:'2026-10-15',age_min:21,age_max:30,age_relaxation:'OBC +3, SC/ST +5',fee_general:1500,fee_reserved:0,vacancies:3630}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'nvs-teacher-tgt-pgt-2026', title: 'NVS Teacher 2026 — TGT/PGT', description: 'Navodaya Vidyalaya Samiti teacher recruitment 2026.\n\n5,841 teaching and non-teaching posts in residential schools.', summary: 'NVS 2026 — 5,841 posts. TGT/PGT teachers in Navodaya residential schools across rural India.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['nvs'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 444000, salary_max: 1260000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 5841, posted_at: ago(144), application_deadline: deadline(25), skills: ['Subject Expertise','Pedagogy','CTET','Residential School Experience','Extracurricular Skills'], qualifications: ['Graduate/Post-graduate with B.Ed'], department: 'Education', industry: 'Government / Education', benefits: ['Pension','DA','Free quarters','Medical','Mess facilities'], apply_mode: 'external', apply_url: 'https://navodaya.gov.in', government_meta: {organization:'NVS',notification_number:'NVS/REC/2026',exam_date:'2026-11-10',age_min:21,age_max:40,age_relaxation:'OBC +3, SC/ST +5',fee_general:1500,fee_reserved:0,vacancies:5841}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'ntpc-graduate-engineer-trainee-2026', title: 'NTPC Graduate Engineer Trainee 2026', description: 'NTPC recruitment for 500+ GET positions through GATE scores.\n\nIndia largest power generation company. Posting at thermal/solar power plants.', summary: 'NTPC GET 2026 — 500+ vacancies via GATE. Power generation PSU.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['ntpc'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 800000, salary_max: 1400000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 500, posted_at: ago(96), application_deadline: deadline(20), skills: ['GATE Score','Engineering','Technical Knowledge','Problem Solving'], qualifications: ['B.E./B.Tech with valid GATE in EE/ME/Civil/Instrumentation'], department: 'Power Generation', industry: 'Government / PSU', benefits: ['Pension','DA','HRA','Medical','Subsidized electricity','Quarters'], apply_mode: 'external', apply_url: 'https://ntpc.co.in/careers', government_meta: {organization:'NTPC',notification_number:'NTPC/GET/2026',age_min:18,age_max:27,age_relaxation:'OBC +3, SC/ST +5',fee_general:300,fee_reserved:0,vacancies:500}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'ongc-graduate-trainee-2026', title: 'ONGC Graduate Trainee 2026', description: 'Graduate Trainee recruitment at India largest oil and gas PSU through GATE.\n\nOne of the best PSU salary packages.', summary: 'ONGC Graduate Trainee 2026 — via GATE. Best-in-class PSU salary package.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['ongc'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 900000, salary_max: 1600000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 600, posted_at: ago(120), application_deadline: deadline(22), skills: ['GATE Score','Petroleum Engineering','Chemical Engineering','Mechanical Engineering','Geoscience'], qualifications: ['B.E./B.Tech/M.Sc with valid GATE score'], department: 'Exploration & Production', industry: 'Government / PSU', benefits: ['Pension','DA','HRA','Medical','LTC','Performance bonus'], apply_mode: 'external', apply_url: 'https://ongcindia.com/careers', government_meta: {organization:'ONGC',notification_number:'ONGC/GT/2026',age_min:18,age_max:28,age_relaxation:'OBC +3, SC/ST +5',fee_general:370,fee_reserved:0,vacancies:600}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'iocl-engineer-officer-2026', title: 'IOCL Engineer/Officer 2026', description: 'Indian Oil Corporation recruitment for Engineers and Officers.\n\nIndia largest commercial enterprise by revenue. Refineries, pipelines, R&D.', summary: 'IOCL Engineer 2026 — via GATE. India largest oil marketing company.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['iocl'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 800000, salary_max: 1400000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 450, posted_at: ago(144), application_deadline: deadline(20), skills: ['GATE Score','Chemical Engineering','Mechanical Engineering','Electrical Engineering'], qualifications: ['B.E./B.Tech with valid GATE score'], department: 'Refining & Pipelines', industry: 'Government / PSU', benefits: ['Pension','DA','HRA','Medical','LTC','Subsidized fuel'], apply_mode: 'external', apply_url: 'https://iocl.com/careers', government_meta: {organization:'IOCL',notification_number:'IOCL/ENG/2026',age_min:18,age_max:26,age_relaxation:'OBC +3, SC/ST +5',fee_general:300,fee_reserved:0,vacancies:450}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'bhel-engineer-trainee-2026', title: 'BHEL Engineer Trainee 2026', description: 'BHEL Engineer Trainee recruitment.\n\nIndia largest power equipment manufacturer. Turbines, generators, defence equipment.', summary: 'BHEL Engineer Trainee 2026 — via GATE. Power equipment manufacturing.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['bhel'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 700000, salary_max: 1200000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 350, posted_at: ago(168), application_deadline: deadline(18), skills: ['GATE Score','Mechanical Engineering','Electrical Engineering','Electronics','Manufacturing'], qualifications: ['B.E./B.Tech with valid GATE score'], department: 'Manufacturing', industry: 'Government / PSU', benefits: ['Pension','DA','HRA','Medical','Quarters'], apply_mode: 'external', apply_url: 'https://bhel.com/careers', government_meta: {organization:'BHEL',notification_number:'BHEL/ET/2026',age_min:18,age_max:27,age_relaxation:'OBC +3, SC/ST +5',fee_general:300,fee_reserved:0,vacancies:350}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'ibps-clerk-2026', title: 'IBPS Clerk 2026', description: 'IBPS Clerk cadre recruitment across participating public sector banks.\n\n8,000 vacancies. Front-desk operations, customer service.', summary: 'IBPS Clerk 2026 — 8,000 vacancies across PSU banks. Graduate eligible.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['ibps'], posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 300000, salary_max: 600000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 8000, posted_at: ago(48), application_deadline: deadline(30), skills: ['Numerical Ability','Reasoning','English','General Awareness','Computer Skills'], qualifications: ['Bachelor degree in any discipline'], department: 'Banking Operations', industry: 'Government / BFSI', benefits: ['Pension','DA','HRA','Medical','Staff loans'], apply_mode: 'external', apply_url: 'https://ibps.in', government_meta: {organization:'IBPS',notification_number:'IBPS/CRP-CLERK-XVI',exam_date:'2026-09-25',age_min:20,age_max:28,age_relaxation:'OBC +3, SC/ST +5',fee_general:850,fee_reserved:175,vacancies:8000}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'state-psc-uppsc-mppsc-bpsc-2026', title: 'State PSC 2026 — UPPSC/MPPSC/BPSC', description: 'State-level civil services examinations for SDM, DSP, BDO, and other administrative posts.\n\nDistrict-level governance roles. 7th Pay Commission.', summary: 'State PSC 2026 — SDM, DSP, BDO posts. UP/MP/Bihar. District-level governance roles.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['state-psc'], posted_by, location_city: 'Lucknow', location_state: 'Uttar Pradesh', location_state_code: 'UP', location_country: 'India', location_country_code: 'IN', salary_min: 444000, salary_max: 1400000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 0, openings: 3000, posted_at: ago(96), application_deadline: deadline(35), skills: ['General Studies','Current Affairs','Hindi','Ethics','Optional Subject','Interview Skills'], qualifications: ['Bachelor degree from recognized university'], department: 'State Administration', industry: 'Government', benefits: ['Pension','DA','HRA','Medical','Government vehicle','Quarters'], apply_mode: 'external', apply_url: 'https://uppsc.up.nic.in', government_meta: {organization:'State PSC',notification_number:'UPPSC/PCS/2026',exam_date:'2026-10-20',age_min:21,age_max:40,age_relaxation:'OBC +3, SC/ST +5',fee_general:125,fee_reserved:65,vacancies:3000}, status: 'active', is_featured: false, is_urgent: false },
    { slug: 'ctet-central-teacher-eligibility-2026', title: 'CTET 2026 — Central Teacher Eligibility Test', description: 'National-level eligibility test mandatory for KVS, NVS, and central government school teaching positions.\n\nCTET qualification valid for life. Paper-I and Paper-II.', summary: 'CTET 2026 — Mandatory for govt teaching jobs. Lifetime validity. Paper I and II.', category: 'government', job_type: 'full_time', work_mode: 'onsite', company_id: co['cbse'], posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 396000, salary_max: 1140000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: false, experience_min: 0, experience_max: 0, openings: 100000, posted_at: ago(24), application_deadline: deadline(40), skills: ['Child Development','Pedagogy','Language','Mathematics','Environmental Studies'], qualifications: ['D.El.Ed or B.Ed from recognized institution'], department: 'Education', industry: 'Government / Education', benefits: ['Opens doors to KVS/NVS/Army schools','Lifetime validity'], apply_mode: 'external', apply_url: 'https://ctet.nic.in', government_meta: {organization:'CBSE',notification_number:'CTET/July/2026',exam_date:'2026-12-10',age_min:18,age_max:99,fee_general:1000,fee_reserved:500,vacancies:100000}, status: 'active', is_featured: false, is_urgent: false, faq: [{q:'Is CTET valid for life?',a:'Yes, from 2024 onwards CTET qualification is valid for lifetime.'},{q:'Can I appear for both papers?',a:'Yes, you can appear for both Paper-I and Paper-II in the same attempt.'}] },
  ]
  await insertJobs(govJobs)
  console.log('Government jobs done!')
}

main().catch(console.error)
