const BASE = 'https://aiycgmrubisaxknbeaov.supabase.co'
const KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpeWNnbXJ1YmlzYXhrbmJlYW92Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTkwODIwNiwiZXhwIjoyMDkxNDg0MjA2fQ.SgdX0RO_yUp1c6iQswTpVQwS8TTdpCo9aXR2qlMa7TQ'
const headers = { 'apikey': KEY, 'Authorization': `Bearer ${KEY}`, 'Content-Type': 'application/json', 'Prefer': 'return=representation' }

async function api(path, opts = {}) {
  const mergedHeaders = { ...headers, ...(opts.headers || {}) }
  const res = await fetch(`${BASE}/rest/v1/${path}`, { method: opts.method || 'GET', headers: mergedHeaders, body: opts.body })
  const text = await res.text()
  if (!res.ok) throw new Error(`${res.status}: ${text}`)
  return text ? JSON.parse(text) : null
}

async function getPosterId() {
  const res = await fetch(`${BASE}/auth/v1/admin/users?per_page=1`, { headers: { ...headers, 'Authorization': `Bearer ${KEY}` } })
  const data = await res.json()
  return data?.users?.[0]?.id
}

async function upsertCompanies(companies) {
  const data = await api('companies?on_conflict=slug', { method: 'POST', body: JSON.stringify(companies), headers: { 'Prefer': 'return=representation,resolution=merge-duplicates' } })
  const map = {}
  data.forEach(c => { map[c.slug] = c.id })
  return map
}

async function insertJobs(jobs) {
  // Normalize: ensure all objects have same keys
  const allKeys = new Set()
  jobs.forEach(j => Object.keys(j).forEach(k => allKeys.add(k)))
  const normalized = jobs.map(j => {
    const obj = {}
    allKeys.forEach(k => { obj[k] = j[k] !== undefined ? j[k] : null })
    return obj
  })
  for (let i = 0; i < normalized.length; i += 10) {
    const batch = normalized.slice(i, i + 10)
    try {
      await api('jobs?on_conflict=slug', { method: 'POST', body: JSON.stringify(batch), headers: { 'Prefer': 'return=minimal,resolution=ignore-duplicates' } })
      console.log(`  Inserted batch ${i / 10 + 1} (${batch.length} jobs)`)
    } catch (e) { console.error(`  Batch ${i / 10 + 1} error:`, e.message) }
  }
}

async function main() {
  const posted_by = await getPosterId()
  if (!posted_by) { console.error('No user found'); process.exit(1) }
  console.log('Using posted_by:', posted_by)

  // === COMPANIES ===
  const companies = [
    { name: 'Google India', slug: 'google-india', website: 'https://careers.google.com', industry: 'Technology', size: '5000+', hq_location: 'Bengaluru, IN', about: 'Global tech leader — Search, Cloud, AI.', is_verified: true },
    { name: 'Microsoft India', slug: 'microsoft-india', website: 'https://careers.microsoft.com', industry: 'Technology', size: '5000+', hq_location: 'Hyderabad, IN', about: 'Enterprise software, Azure cloud, AI.', is_verified: true },
    { name: 'Amazon India', slug: 'amazon-india', website: 'https://amazon.jobs', industry: 'E-commerce / Tech', size: '5000+', hq_location: 'Bengaluru, IN', about: 'E-commerce, AWS, logistics.', is_verified: true },
    { name: 'Flipkart', slug: 'flipkart', website: 'https://flipkart.com', industry: 'E-commerce', size: '5000+', hq_location: 'Bengaluru, IN', about: 'India largest e-commerce marketplace.', is_verified: true },
    { name: 'Razorpay', slug: 'razorpay', website: 'https://razorpay.com', industry: 'Fintech', size: '1001-5000', hq_location: 'Bengaluru, IN', about: 'Payment gateway and financial services.', is_verified: true },
    { name: 'PhonePe', slug: 'phonepe', website: 'https://phonepe.com', industry: 'Fintech', size: '5000+', hq_location: 'Bengaluru, IN', about: 'India leading UPI payments platform.', is_verified: true },
    { name: 'CRED', slug: 'cred', website: 'https://cred.club', industry: 'Fintech', size: '201-1000', hq_location: 'Bengaluru, IN', about: 'Premium credit card rewards platform.', is_verified: true },
    { name: 'Swiggy', slug: 'swiggy', website: 'https://swiggy.com', industry: 'Food Tech', size: '5000+', hq_location: 'Bengaluru, IN', about: 'Food delivery and quick commerce.', is_verified: true },
    { name: 'Zomato', slug: 'zomato', website: 'https://zomato.com', industry: 'Food Tech', size: '5000+', hq_location: 'Gurgaon, IN', about: 'Food delivery, dining, and quick commerce.', is_verified: true },
    { name: 'Meesho', slug: 'meesho', website: 'https://meesho.com', industry: 'E-commerce', size: '1001-5000', hq_location: 'Bengaluru, IN', about: 'Social commerce platform for small businesses.', is_verified: true },
    { name: 'Groww', slug: 'groww', website: 'https://groww.in', industry: 'Fintech', size: '1001-5000', hq_location: 'Bengaluru, IN', about: 'Investment platform — stocks, MFs, FDs.', is_verified: true },
    { name: 'Zerodha', slug: 'zerodha', website: 'https://zerodha.com', industry: 'Fintech', size: '201-1000', hq_location: 'Bengaluru, IN', about: 'India largest retail stockbroker.', is_verified: true },
    { name: 'TCS', slug: 'tcs', website: 'https://tcs.com', industry: 'IT Services', size: '5000+', hq_location: 'Mumbai, IN', about: 'Tata Consultancy Services — global IT leader.', is_verified: true },
    { name: 'Infosys', slug: 'infosys', website: 'https://infosys.com', industry: 'IT Services', size: '5000+', hq_location: 'Bengaluru, IN', about: 'Global IT consulting and services.', is_verified: true },
    { name: 'Wipro', slug: 'wipro', website: 'https://wipro.com', industry: 'IT Services', size: '5000+', hq_location: 'Bengaluru, IN', about: 'Global IT, consulting, and business services.', is_verified: true },
    { name: 'HCLTech', slug: 'hcltech', website: 'https://hcltech.com', industry: 'IT Services', size: '5000+', hq_location: 'Noida, IN', about: 'Global technology company.', is_verified: true },
    { name: 'Paytm', slug: 'paytm', website: 'https://paytm.com', industry: 'Fintech', size: '5000+', hq_location: 'Noida, IN', about: 'Digital payments and financial services.', is_verified: true },
    { name: 'Salesforce India', slug: 'salesforce-india', website: 'https://salesforce.com', industry: 'Technology', size: '5000+', hq_location: 'Hyderabad, IN', about: 'Global CRM and enterprise cloud.', is_verified: true },
    { name: 'Deloitte India', slug: 'deloitte-india', website: 'https://deloitte.com', industry: 'Consulting', size: '5000+', hq_location: 'Mumbai, IN', about: 'Big Four — audit, consulting, advisory.', is_verified: true },
    { name: 'Accenture India', slug: 'accenture-india', website: 'https://accenture.com', industry: 'IT Services', size: '5000+', hq_location: 'Chennai, IN', about: 'Global consulting and IT services.', is_verified: true },
    { name: 'Ola', slug: 'ola', website: 'https://olacabs.com', industry: 'Mobility', size: '1001-5000', hq_location: 'Bengaluru, IN', about: 'Ride-hailing and electric vehicles.', is_verified: true },
    { name: 'Nykaa', slug: 'nykaa', website: 'https://nykaa.com', industry: 'E-commerce', size: '1001-5000', hq_location: 'Mumbai, IN', about: 'Beauty and fashion e-commerce.', is_verified: true },
    { name: 'Jio Platforms', slug: 'jio-platforms', website: 'https://jio.com', industry: 'Telecom', size: '5000+', hq_location: 'Mumbai, IN', about: 'India largest telecom and digital services.', is_verified: true },
    { name: 'Adobe India', slug: 'adobe-india', website: 'https://adobe.com', industry: 'Technology', size: '5000+', hq_location: 'Noida, IN', about: 'Creative and document cloud software.', is_verified: true },
    { name: 'Goldman Sachs India', slug: 'goldman-sachs-india', website: 'https://goldmansachs.com', industry: 'BFSI', size: '5000+', hq_location: 'Bengaluru, IN', about: 'Global investment banking and securities.', is_verified: true },
    { name: 'Bosch India', slug: 'bosch-india', website: 'https://bosch.in', industry: 'Manufacturing', size: '5000+', hq_location: 'Bengaluru, IN', about: 'Auto components, IoT, engineering.', is_verified: true },
    { name: 'upGrad', slug: 'upgrad', website: 'https://upgrad.com', industry: 'EdTech', size: '1001-5000', hq_location: 'Mumbai, IN', about: 'Online higher education platform.', is_verified: true },
    { name: 'CoinDCX', slug: 'coindcx', website: 'https://coindcx.com', industry: 'Crypto / Fintech', size: '51-200', hq_location: 'Mumbai, IN', about: 'India leading crypto exchange.', is_verified: true },
    { name: 'SSC', slug: 'ssc', website: 'https://ssc.gov.in', industry: 'Government', size: '5000+', hq_location: 'New Delhi, IN', about: 'Staff Selection Commission.', is_verified: true },
    { name: 'IBPS', slug: 'ibps', website: 'https://ibps.in', industry: 'Government', size: '5000+', hq_location: 'Mumbai, IN', about: 'Institute of Banking Personnel Selection.', is_verified: true },
    { name: 'RBI', slug: 'rbi', website: 'https://rbi.org.in', industry: 'Government / BFSI', size: '5000+', hq_location: 'Mumbai, IN', about: 'Reserve Bank of India — central bank.', is_verified: true },
    { name: 'RRB', slug: 'rrb', website: 'https://rrbcdg.gov.in', industry: 'Government', size: '5000+', hq_location: 'New Delhi, IN', about: 'Railway Recruitment Board.', is_verified: true },
    { name: 'DRDO', slug: 'drdo', website: 'https://drdo.gov.in', industry: 'Government / Defence', size: '5000+', hq_location: 'New Delhi, IN', about: 'Defence Research and Development Organisation.', is_verified: true },
    { name: 'Indian Army', slug: 'indian-army', website: 'https://joinindianarmy.nic.in', industry: 'Government / Defence', size: '5000+', hq_location: 'New Delhi, IN', about: 'Indian Armed Forces — Army.', is_verified: true },
    { name: 'Indian Navy', slug: 'indian-navy', website: 'https://joinindiannavy.gov.in', industry: 'Government / Defence', size: '5000+', hq_location: 'New Delhi, IN', about: 'Indian Armed Forces — Navy.', is_verified: true },
    { name: 'Indian Air Force', slug: 'indian-air-force', website: 'https://indianairforce.nic.in', industry: 'Government / Defence', size: '5000+', hq_location: 'New Delhi, IN', about: 'Indian Armed Forces — Air Force.', is_verified: true },
    { name: 'KVS', slug: 'kvs', website: 'https://kvsangathan.nic.in', industry: 'Government / Education', size: '5000+', hq_location: 'New Delhi, IN', about: 'Kendriya Vidyalaya Sangathan.', is_verified: true },
    { name: 'NVS', slug: 'nvs', website: 'https://navodaya.gov.in', industry: 'Government / Education', size: '5000+', hq_location: 'New Delhi, IN', about: 'Navodaya Vidyalaya Samiti.', is_verified: true },
    { name: 'NTPC', slug: 'ntpc', website: 'https://ntpc.co.in', industry: 'Government / PSU', size: '5000+', hq_location: 'New Delhi, IN', about: 'India largest power generation company.', is_verified: true },
    { name: 'ONGC', slug: 'ongc', website: 'https://ongcindia.com', industry: 'Government / PSU', size: '5000+', hq_location: 'New Delhi, IN', about: 'Oil and Natural Gas Corporation.', is_verified: true },
    { name: 'IOCL', slug: 'iocl', website: 'https://iocl.com', industry: 'Government / PSU', size: '5000+', hq_location: 'New Delhi, IN', about: 'Indian Oil Corporation Limited.', is_verified: true },
    { name: 'BHEL', slug: 'bhel', website: 'https://bhel.com', industry: 'Government / PSU', size: '5000+', hq_location: 'New Delhi, IN', about: 'Bharat Heavy Electricals Limited.', is_verified: true },
    { name: 'State PSC', slug: 'state-psc', website: 'https://uppsc.up.nic.in', industry: 'Government', size: '5000+', hq_location: 'Lucknow, IN', about: 'State Public Service Commissions.', is_verified: true },
    { name: 'CBSE', slug: 'cbse', website: 'https://cbse.gov.in', industry: 'Government / Education', size: '5000+', hq_location: 'New Delhi, IN', about: 'Central Board of Secondary Education.', is_verified: true },
    { name: 'Dunzo', slug: 'dunzo', website: 'https://dunzo.com', industry: 'Quick Commerce', size: '201-1000', hq_location: 'Bengaluru, IN', about: 'Quick commerce and hyperlocal delivery.', is_verified: true },
    { name: 'Tata Group', slug: 'tata-group', website: 'https://tata.com', industry: 'Conglomerate', size: '5000+', hq_location: 'Mumbai, IN', about: 'India largest conglomerate.', is_verified: true },
  ]

  console.log('Upserting companies...')
  const companyMap = await upsertCompanies(companies)
  console.log(`  ${Object.keys(companyMap).length} companies ready`)

  // Helper
  const co = (slug) => companyMap[slug]
  const deadline = (days) => new Date(Date.now() + days * 86400000).toISOString().split('T')[0]
  const ago = (hours) => new Date(Date.now() - hours * 3600000).toISOString()

  // === PRIVATE JOBS ===
  console.log('\nInserting PRIVATE jobs...')
  const privateJobs = [
    { slug: 'senior-ai-ml-engineer-bengaluru-g001', title: 'Senior AI/ML Engineer', description: 'Design and deploy large-scale AI/ML models for Google Cloud and Search products.\n\nResponsibilities\n- Build and fine-tune LLM architectures for production use.\n- Design ML pipelines using TensorFlow and JAX.\n- Collaborate with research teams on cutting-edge AI systems.\n\nRequirements\n- 3+ years in ML/AI with production deployments.\n- Strong Python, deep learning frameworks, and MLOps experience.', summary: 'Build large-scale AI/ML models for Google Cloud and Search — LLMs, TensorFlow, MLOps.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('google-india'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 3500000, salary_max: 7500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 3, experience_max: 8, openings: 3, posted_at: ago(24), application_deadline: deadline(30), skills: ['Python','TensorFlow','PyTorch','LLMs','NLP','Deep Learning','MLOps','Cloud AI'], qualifications: ['B.Tech/M.Tech in CS/AI/ML'], department: 'AI Research', industry: 'Technology', benefits: ['Health insurance','RSUs','Free meals','Gym','Learning budget'], apply_mode: 'external', apply_url: 'https://careers.google.com', status: 'active', is_featured: true, is_urgent: false },
    { slug: 'full-stack-developer-sde2-hyderabad-m001', title: 'Full Stack Developer (SDE-2)', description: 'Build enterprise-grade applications on Azure cloud platform.\n\nWhat you will do\n- Develop features for Microsoft 365 and Teams.\n- Work with React, Node.js, and C#/.NET.\n- Collaborate with cross-functional teams globally.\n\nRequirements\n- 2+ years full-stack development experience.\n- Proficiency in TypeScript and system design.', summary: 'Build enterprise apps for Microsoft 365 and Teams — React, Node.js, Azure, TypeScript.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('microsoft-india'), posted_by, location_city: 'Hyderabad', location_state: 'Telangana', location_state_code: 'TG', location_country: 'India', location_country_code: 'IN', salary_min: 2500000, salary_max: 5500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 6, openings: 5, posted_at: ago(48), application_deadline: deadline(28), skills: ['React','Node.js','TypeScript','Azure','C#','.NET','System Design','SQL'], qualifications: ['B.Tech in CS or related'], department: 'Engineering', industry: 'Technology', benefits: ['Health insurance','RSUs','Annual bonus','Flexible hours'], apply_mode: 'external', apply_url: 'https://careers.microsoft.com', status: 'active', is_featured: true, is_urgent: false },
    { slug: 'cloud-solutions-architect-gurgaon-a001', title: 'Cloud Solutions Architect', description: 'Design cloud-native architectures for enterprise clients migrating to AWS.\n\nResponsibilities\n- Lead technical workshops and architecture reviews.\n- Guide mission-critical workload migrations.\n- Work with Kubernetes, Terraform, and serverless.', summary: 'Design cloud-native architectures for enterprise AWS migrations — Kubernetes, Terraform, serverless.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('amazon-india'), posted_by, location_city: 'Gurgaon', location_state: 'Haryana', location_state_code: 'HR', location_country: 'India', location_country_code: 'IN', salary_min: 3000000, salary_max: 6500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 4, experience_max: 10, openings: 2, posted_at: ago(72), application_deadline: deadline(25), skills: ['AWS','Kubernetes','Docker','Terraform','Python','Microservices','Serverless','CI/CD'], qualifications: ['B.Tech in CS','AWS certifications preferred'], department: 'Cloud Architecture', industry: 'Technology', benefits: ['Health insurance','RSUs','Relocation support'], apply_mode: 'external', apply_url: 'https://amazon.jobs', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'devops-engineer-bengaluru-f001', title: 'DevOps Engineer', description: 'Manage and scale Flipkart infrastructure serving 500M+ users.\n\n- Build robust CI/CD pipelines.\n- Ensure 99.99% uptime during high-traffic sale events.\n- Manage Kubernetes clusters at scale.', summary: 'Scale Flipkart infrastructure for 500M+ users — Kubernetes, CI/CD, 99.99% uptime.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('flipkart'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 1800000, salary_max: 3500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 6, openings: 3, posted_at: ago(24), application_deadline: deadline(21), skills: ['Kubernetes','Docker','Jenkins','Terraform','AWS','Linux','Python','Prometheus'], qualifications: ['B.Tech in CS or related'], department: 'Platform Engineering', industry: 'E-commerce', benefits: ['Health insurance','ESOPs','Free meals','Flexible hours'], apply_mode: 'external', apply_url: 'https://flipkart.com/careers', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'backend-engineer-payments-bengaluru-r001', title: 'Backend Engineer (Payments)', description: 'Build and scale payment processing systems handling millions of daily transactions.\n\n- Design high-throughput, low-latency distributed systems.\n- Own microservices powering India digital payments.', summary: 'Build payment systems handling millions of daily txns — Go, Java, Kafka, PostgreSQL.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('razorpay'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 2000000, salary_max: 4200000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 5, openings: 4, posted_at: ago(4), application_deadline: deadline(25), skills: ['Go','Java','Microservices','PostgreSQL','Redis','Kafka','System Design','API Design'], qualifications: ['B.Tech in CS or related'], department: 'Payments Engineering', industry: 'Fintech', benefits: ['Health insurance','ESOPs','Learning budget','Gym membership'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: true },
    { slug: 'data-scientist-bengaluru-pp001', title: 'Data Scientist', description: 'Drive data-driven decision-making for PhonePe 500M+ user base.\n\n- Build predictive models for fraud detection and user engagement.\n- Run A/B tests and optimize transaction flows.', summary: 'Build ML models for fraud detection and user engagement — Python, Spark, 500M+ users.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('phonepe'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 1800000, salary_max: 4000000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 5, openings: 2, posted_at: ago(48), application_deadline: deadline(22), skills: ['Python','SQL','Machine Learning','Statistics','A/B Testing','Spark','Pandas','Tableau'], qualifications: ['B.Tech/M.Tech in CS/Stats/Math'], department: 'Data Science', industry: 'Fintech', benefits: ['Health insurance','ESOPs','Free meals','Wellness program'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'cybersecurity-analyst-mumbai-tcs001', title: 'Cybersecurity Analyst', description: 'Monitor and protect enterprise client infrastructure from cyber threats.\n\n- Conduct vulnerability assessments and penetration testing.\n- Lead incident response for Fortune 500 clients.', summary: 'Protect Fortune 500 client infrastructure — SIEM, penetration testing, incident response.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('tcs'), posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 800000, salary_max: 1800000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 1, experience_max: 5, openings: 6, posted_at: ago(72), application_deadline: deadline(30), skills: ['SIEM','Network Security','Penetration Testing','SOC','Firewalls','Incident Response'], qualifications: ['B.Tech in CS/IT','CISSP or CEH preferred'], department: 'Cybersecurity', industry: 'IT Services', benefits: ['Health insurance','PF','Annual bonus','Training budget'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'software-developer-sde1-pune-inf001', title: 'Software Development Engineer (SDE-1)', description: 'Develop enterprise applications for global clients in BFSI and retail.\n\n- Build and maintain Java/Spring Boot applications.\n- Write REST APIs and integrate with databases.', summary: 'Build enterprise Java/Spring Boot apps for BFSI and retail clients — REST APIs, Agile.', category: 'private', job_type: 'full_time', work_mode: 'onsite', company_id: co('infosys'), posted_by, location_city: 'Pune', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 600000, salary_max: 1200000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 0, experience_max: 2, openings: 15, posted_at: ago(120), application_deadline: deadline(35), skills: ['Java','Spring Boot','REST APIs','MySQL','Git','Agile','Data Structures'], qualifications: ['B.Tech in CS/IT'], department: 'Engineering', industry: 'IT Services', benefits: ['Health insurance','PF','Training program','Relocation support'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'generative-ai-engineer-bengaluru-cr001', title: 'Generative AI Engineer', description: 'Build AI-powered features for CRED premium fintech platform.\n\n- Design and deploy RAG pipelines and LLM applications.\n- Build personalized financial recommendation systems.', summary: 'Build GenAI features for CRED — RAG, LangChain, LLMs, personalized finance recommendations.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('cred'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 2500000, salary_max: 5500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 5, openings: 2, posted_at: ago(6), application_deadline: deadline(20), skills: ['Python','LLMs','RAG','LangChain','OpenAI API','Vector Databases','NLP','Prompt Engineering'], qualifications: ['B.Tech/M.Tech in CS/AI'], department: 'AI Engineering', industry: 'Fintech', benefits: ['Health insurance','ESOPs','Learning budget','Free meals'], apply_mode: 'internal', status: 'active', is_featured: true, is_urgent: true },
    { slug: 'product-manager-bengaluru-sw001', title: 'Product Manager — Quick Commerce', description: 'Lead product strategy for Swiggy quick commerce vertical.\n\n- Define roadmap and prioritize features.\n- Run experiments and drive growth metrics.', summary: 'Lead quick-commerce product strategy — roadmap, A/B tests, growth metrics.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('swiggy'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 2200000, salary_max: 4500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 3, experience_max: 7, openings: 2, posted_at: ago(48), application_deadline: deadline(24), skills: ['Product Strategy','Analytics','SQL','A/B Testing','Agile','User Research','PRDs'], qualifications: ['MBA or B.Tech with PM experience'], department: 'Product', industry: 'Food Tech', benefits: ['Health insurance','ESOPs','Free Swiggy credits','Flexible hours'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'frontend-engineer-react-bengaluru-me001', title: 'Frontend Engineer (React)', description: 'Build performant mobile-first web experiences for 150M+ users.\n\n- Optimize page load times for Tier 2/3 city users.\n- Work with React, Next.js, and TypeScript.', summary: 'Build mobile-first React/Next.js apps for 150M+ users — performance, conversion optimization.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('meesho'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 1500000, salary_max: 3000000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 5, openings: 3, posted_at: ago(24), application_deadline: deadline(28), skills: ['React','JavaScript','TypeScript','Next.js','CSS','Performance Optimization','Redux'], qualifications: ['B.Tech in CS or related'], department: 'Frontend Engineering', industry: 'E-commerce', benefits: ['Health insurance','ESOPs','Free meals','Learning budget'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'quantitative-analyst-bengaluru-z001', title: 'Quantitative Analyst', description: 'Develop quantitative models for India largest retail stockbroker.\n\n- Analyze trading patterns for 15M+ investors.\n- Build risk management frameworks.', summary: 'Build quant models for Zerodha — trading analytics, risk modeling, 15M+ investors.', category: 'private', job_type: 'full_time', work_mode: 'onsite', company_id: co('zerodha'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 1500000, salary_max: 3500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 1, experience_max: 4, openings: 2, posted_at: ago(96), application_deadline: deadline(26), skills: ['Python','Statistics','Financial Markets','SQL','Machine Learning','R','Time Series Analysis'], qualifications: ['B.Tech/M.Tech in CS/Math/Stats'], department: 'Quant Research', industry: 'Fintech', benefits: ['Health insurance','Profit sharing','Learning budget'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'growth-marketing-manager-bengaluru-gr001', title: 'Growth Marketing Manager', description: 'Drive user acquisition and retention for Groww investment platform.\n\n- Plan multi-channel marketing campaigns.\n- Optimize Google Ads and social media spend.', summary: 'Drive user acquisition — Google Ads, social media, content strategy, funnel optimization.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('groww'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 1500000, salary_max: 3000000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 3, experience_max: 6, openings: 2, posted_at: ago(72), application_deadline: deadline(22), skills: ['Digital Marketing','Google Ads','Facebook Ads','SEO','Analytics','Content Strategy','CRM'], qualifications: ['MBA Marketing or equivalent'], department: 'Marketing', industry: 'Fintech', benefits: ['Health insurance','ESOPs','Flexible hours'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'site-reliability-engineer-gurgaon-zm001', title: 'Site Reliability Engineer (SRE)', description: 'Ensure reliability of Zomato food delivery and quick-commerce infrastructure.\n\n- Manage systems handling millions of daily orders.\n- Build monitoring and alerting systems.', summary: 'SRE for Zomato — millions of daily orders, monitoring, SLA management, peak-hour reliability.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('zomato'), posted_by, location_city: 'Gurgaon', location_state: 'Haryana', location_state_code: 'HR', location_country: 'India', location_country_code: 'IN', salary_min: 2000000, salary_max: 4000000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 3, experience_max: 7, openings: 2, posted_at: ago(24), application_deadline: deadline(21), skills: ['Go','Python','Kubernetes','AWS','Terraform','Monitoring','Linux','Distributed Systems'], qualifications: ['B.Tech in CS or related'], department: 'Platform Engineering', industry: 'Food Tech', benefits: ['Health insurance','ESOPs','Free Zomato credits','Gym'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'data-engineer-hyderabad-wi001', title: 'Data Engineer', description: 'Design and build data pipelines for enterprise clients.\n\n- Process terabytes of data for analytics and ML workflows.\n- Work with Spark, Airflow, and cloud data warehouses.', summary: 'Build data pipelines — Spark, Airflow, Snowflake, ETL for healthcare and banking clients.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('wipro'), posted_by, location_city: 'Hyderabad', location_state: 'Telangana', location_state_code: 'TG', location_country: 'India', location_country_code: 'IN', salary_min: 800000, salary_max: 2000000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 1, experience_max: 4, openings: 5, posted_at: ago(120), application_deadline: deadline(30), skills: ['Python','SQL','Spark','Airflow','AWS','ETL','Data Warehousing','Snowflake'], qualifications: ['B.Tech in CS/IT'], department: 'Data Engineering', industry: 'IT Services', benefits: ['Health insurance','PF','Annual bonus','Training'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'ui-ux-designer-noida-pt001', title: 'UI/UX Designer', description: 'Design intuitive experiences for Paytm suite of financial products.\n\n- Create design systems for payments, banking, and insurance.\n- Conduct user research and usability testing.', summary: 'Design experiences for 350M+ users — payments, banking, insurance. Figma, design systems.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('paytm'), posted_by, location_city: 'Noida', location_state: 'Uttar Pradesh', location_state_code: 'UP', location_country: 'India', location_country_code: 'IN', salary_min: 1000000, salary_max: 2200000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 5, openings: 2, posted_at: ago(48), application_deadline: deadline(25), skills: ['Figma','User Research','Wireframing','Prototyping','Design Systems','Accessibility'], qualifications: ['B.Des/M.Des or portfolio'], department: 'Design', industry: 'Fintech', benefits: ['Health insurance','ESOPs','Free meals'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'sap-consultant-chennai-acc001', title: 'SAP S/4HANA Consultant', description: 'Lead SAP S/4HANA implementations for enterprise clients.\n\n- Provide functional and technical ERP consulting.\n- Lead data migration and integration projects.', summary: 'Lead SAP S/4HANA implementations — ERP consulting, data migration, digital transformation.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('accenture-india'), posted_by, location_city: 'Chennai', location_state: 'Tamil Nadu', location_state_code: 'TN', location_country: 'India', location_country_code: 'IN', salary_min: 1000000, salary_max: 2500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 3, experience_max: 8, openings: 4, posted_at: ago(144), application_deadline: deadline(28), skills: ['SAP S/4HANA','ABAP','SAP FICO','ERP','Integration','Data Migration','Consulting'], qualifications: ['B.Tech/MBA','SAP certification preferred'], department: 'Consulting', industry: 'IT Services', benefits: ['Health insurance','PF','Annual bonus','International travel'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'hr-business-partner-noida-hcl001', title: 'HR Business Partner', description: 'Partner with business leaders to align HR strategies with organizational goals.\n\n- Drive talent acquisition and retention programs.\n- Lead workforce planning for 200K+ employee base.', summary: 'HRBP for 200K+ workforce — talent strategy, workforce planning, employee engagement.', category: 'private', job_type: 'full_time', work_mode: 'onsite', company_id: co('hcltech'), posted_by, location_city: 'Noida', location_state: 'Uttar Pradesh', location_state_code: 'UP', location_country: 'India', location_country_code: 'IN', salary_min: 1200000, salary_max: 2200000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 5, experience_max: 10, openings: 2, posted_at: ago(96), application_deadline: deadline(20), skills: ['HR Strategy','Talent Management','Employee Relations','HRIS','Performance Management'], qualifications: ['MBA HR'], department: 'Human Resources', industry: 'IT Services', benefits: ['Health insurance','PF','Annual bonus','Employee discounts'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'enterprise-sales-manager-mumbai-sf001', title: 'Sales Manager — Enterprise', description: 'Drive enterprise CRM sales across India BFSI and manufacturing sectors.\n\n- Manage end-to-end sales cycles for mid-market and large accounts.\n- Present solutions to C-level executives.', summary: 'Enterprise Salesforce CRM sales — BFSI and manufacturing, C-level presentations, deal closing.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('salesforce-india'), posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 1800000, salary_max: 3500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 4, experience_max: 8, openings: 3, posted_at: ago(72), application_deadline: deadline(30), skills: ['Enterprise Sales','CRM','Solution Selling','Negotiation','Account Management','SaaS'], qualifications: ['MBA preferred'], department: 'Sales', industry: 'Technology', benefits: ['Health insurance','Commission','RSUs','Travel allowance'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'financial-analyst-mumbai-dl001', title: 'Financial Analyst', description: 'Perform financial analysis and valuation for M&A advisory engagements.\n\n- Build financial models and DCF valuations.\n- Support audit and due diligence engagements.', summary: 'Financial modeling, valuation, M&A advisory — Excel, Power BI, GAAP/IFRS.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('deloitte-india'), posted_by, location_city: 'Mumbai', location_state: 'Maharashtra', location_state_code: 'MH', location_country: 'India', location_country_code: 'IN', salary_min: 800000, salary_max: 1800000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 1, experience_max: 4, openings: 5, posted_at: ago(48), application_deadline: deadline(22), skills: ['Financial Modeling','Excel','Valuation','Accounting','SQL','Power BI','Risk Analysis'], qualifications: ['CA/CFA/MBA Finance'], department: 'Advisory', industry: 'Consulting', benefits: ['Health insurance','Performance bonus','Learning budget','Travel'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'android-developer-bengaluru-ola001', title: 'Mobile App Developer (Android)', description: 'Build and optimize Ola rider and driver Android apps.\n\n- Work on location-based services and real-time tracking.\n- Optimize app performance for low-end devices.', summary: 'Build Ola Android apps — location services, real-time tracking, Kotlin, Jetpack Compose.', category: 'private', job_type: 'full_time', work_mode: 'hybrid', company_id: co('ola'), posted_by, location_city: 'Bengaluru', location_state: 'Karnataka', location_state_code: 'KA', location_country: 'India', location_country_code: 'IN', salary_min: 1400000, salary_max: 2800000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 2, experience_max: 5, openings: 3, posted_at: ago(24), application_deadline: deadline(24), skills: ['Kotlin','Android SDK','Jetpack Compose','MVVM','REST APIs','Firebase','Git'], qualifications: ['B.Tech in CS or related'], department: 'Mobile Engineering', industry: 'Mobility', benefits: ['Health insurance','ESOPs','Free Ola rides','Learning budget'], apply_mode: 'internal', status: 'active', is_featured: false, is_urgent: false },
    { slug: 'operations-manager-delhi-amz001', title: 'Operations Manager — Fulfilment', description: 'Manage Amazon fulfilment center operations.\n\n- Optimize delivery speed and reduce costs.\n- Lead teams of 100+ associates.\n- Drive process improvement using Lean and Six Sigma.', summary: 'Manage fulfilment center ops — Lean, Six Sigma, 100+ team, delivery optimization.', category: 'private', job_type: 'full_time', work_mode: 'onsite', company_id: co('amazon-india'), posted_by, location_city: 'New Delhi', location_state: 'Delhi', location_state_code: 'DL', location_country: 'India', location_country_code: 'IN', salary_min: 1200000, salary_max: 2500000, salary_currency: 'INR', salary_period: 'year', is_salary_disclosed: true, experience_min: 3, experience_max: 7, openings: 4, posted_at: ago(120), application_deadline: deadline(30), skills: ['Supply Chain','Logistics','Lean Management','Data Analysis','Team Leadership','Six Sigma'], qualifications: ['MBA/B.Tech with ops experience'], department: 'Operations', industry: 'E-commerce', benefits: ['Health insurance','RSUs','Relocation support','PF'], apply_mode: 'external', apply_url: 'https://amazon.jobs', status: 'active', is_featured: false, is_urgent: false },
  ]
  await insertJobs(privateJobs)

  console.log('\nDone! Run the govt and internship scripts next.')
}

main().catch(console.error)
