-- ============================================================================
-- Seed: GOVERNMENT JOBS (22 jobs) — July 2026
-- Requires seed_new_jobs_july2026.sql to be run first (for companies + ctx)
-- Safe to re-run: ON CONFLICT DO NOTHING on slug.
-- ============================================================================

-- Resolve recruiter UUID
do $$
declare
  v_user_id uuid;
  v_override text;
begin
  begin v_override := current_setting('seed.recruiter_uuid', true);
  exception when others then v_override := null; end;
  if v_override is not null and v_override <> '' then v_user_id := v_override::uuid;
  else select id into v_user_id from auth.users order by created_at asc limit 1; end if;
  if v_user_id is null then raise exception 'Seed aborted: no posted_by UUID.'; end if;
  drop table if exists pg_temp.seed_ctx;
  create temp table pg_temp.seed_ctx (user_id uuid not null);
  insert into pg_temp.seed_ctx values (v_user_id);
end $$;

-- Government Jobs
insert into public.jobs (
  slug, title, description, summary, category, job_type, work_mode,
  company_id, posted_by,
  location_city, location_state, location_state_code, location_country, location_country_code,
  salary_min, salary_max, salary_currency, salary_period, is_salary_disclosed,
  experience_min, experience_max, openings,
  posted_at, application_deadline,
  skills, qualifications, department, industry, benefits,
  apply_mode, apply_url, apply_email, apply_phone,
  government_meta, status, is_featured, is_urgent,
  meta_title, meta_description, faq
)
select v.*
from (values

  -- G1. SSC CGL 2026
  ('ssc-cgl-2026-combined-graduate-level',
   'SSC CGL 2026 — Combined Graduate Level',
   E'Staff Selection Commission Combined Graduate Level Examination 2026.\n\n12,256 vacancies across central government ministries.\nPosts include Tax Assistant, Auditor, Inspector, Sub-Inspector, and Section Officer.\n\nTier 1 exam: August-September 2026.\nTier 2 exam: November 2026.',
   'SSC CGL 2026 — 12,256 vacancies. Tax Assistant, Auditor, Inspector, Section Officer posts.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'ssc'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   420000, 900000, 'INR', 'year', true,
   0, 0, 12256,
   now() - interval '1 day', (current_date + 30)::date,
   ARRAY['Quantitative Aptitude','Reasoning','English','General Awareness','Computer Proficiency'],
   ARRAY['Bachelor degree from recognized university'],
   'Multiple Ministries', 'Government',
   ARRAY['Pension','DA','HRA','Medical','LTC'],
   'external'::public.apply_mode, 'https://ssc.gov.in', null, null,
   '{"organization":"SSC","notification_number":"SSC/CGL/2026","notification_pdf_url":"https://ssc.gov.in/cgl-2026.pdf","exam_date":"2026-08-20","age_min":18,"age_max":32,"age_relaxation":"OBC +3, SC/ST +5","fee_general":100,"fee_reserved":0,"vacancies":12256}'::jsonb,
   'active'::public.job_status, true, true, null, null,
   '[{"q":"What is the eligibility for SSC CGL?","a":"Bachelor degree from a recognized university. Age 18-32 years (relaxation for reserved categories)."},{"q":"What is the exam pattern?","a":"Tier 1 (objective MCQ), Tier 2 (descriptive + MCQ), followed by document verification."}]'::jsonb),

  -- G2. SSC CHSL 2026
  ('ssc-chsl-2026-higher-secondary-level',
   'SSC CHSL 2026 — Combined Higher Secondary Level',
   E'SSC CHSL Examination 2026 for LDC, Junior Secretariat Assistant, Data Entry Operator, and Postal Assistant posts.\n\n3,500+ vacancies across central government offices.\nMinimum qualification: Class 12 pass.\nIdeal for 12th pass candidates seeking government careers.',
   'SSC CHSL 2026 — 3,500+ vacancies. LDC, JSA, DEO, Postal Assistant posts. 12th pass eligible.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'ssc'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   252000, 540000, 'INR', 'year', true,
   0, 0, 3500,
   now() - interval '3 days', (current_date + 35)::date,
   ARRAY['English','Quantitative Aptitude','Reasoning','General Awareness','Typing Speed'],
   ARRAY['Class 12 pass from recognized board'],
   'Multiple Ministries', 'Government',
   ARRAY['Pension','DA','HRA','Medical'],
   'external'::public.apply_mode, 'https://ssc.gov.in', null, null,
   '{"organization":"SSC","notification_number":"SSC/CHSL/2026","notification_pdf_url":"https://ssc.gov.in/chsl-2026.pdf","exam_date":"2026-09-15","age_min":18,"age_max":27,"age_relaxation":"OBC +3, SC/ST +5","fee_general":100,"fee_reserved":0,"vacancies":3500}'::jsonb,
   'active'::public.job_status, true, false, null, null, null::jsonb),

  -- G3. IBPS PO 2026
  ('ibps-po-2026-probationary-officer',
   'IBPS PO 2026 — Probationary Officer',
   E'IBPS PO/MT recruitment 2026 for 6,715 vacancies across participating public sector banks.\n\n29% increase in vacancies from last year.\nPrelims: August 2026. Mains: October 2026.\nStarting salary approx ₹44,000/month + allowances.',
   'IBPS PO 2026 — 6,715 vacancies (29% increase). Bank Probationary Officer across PSU banks.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'ibps'), (select user_id from pg_temp.seed_ctx limit 1),
   'Mumbai', 'Maharashtra', 'MH', 'India', 'IN',
   528000, 1080000, 'INR', 'year', true,
   0, 0, 6715,
   now() - interval '2 days', (current_date + 28)::date,
   ARRAY['Quantitative Aptitude','Reasoning','English','Banking Awareness','Computer Knowledge'],
   ARRAY['Bachelor degree in any discipline'],
   'Banking Operations', 'Government / BFSI',
   ARRAY['DA','HRA','Pension','Medical','Leased accommodation'],
   'external'::public.apply_mode, 'https://ibps.in', null, null,
   '{"organization":"IBPS","notification_number":"IBPS/CRP-PO/MT-XVI","notification_pdf_url":"https://ibps.in/po-2026.pdf","exam_date":"2026-08-15","age_min":20,"age_max":30,"age_relaxation":"OBC +3, SC/ST +5","fee_general":850,"fee_reserved":175,"vacancies":6715}'::jsonb,
   'active'::public.job_status, true, true, null, null,
   '[{"q":"Which banks participate in IBPS PO?","a":"All nationalized banks except SBI — PNB, BOB, Canara Bank, Union Bank, Indian Bank, etc."},{"q":"What is the starting salary?","a":"Approx ₹44,000/month basic + DA, HRA, and other allowances totaling ₹55,000-60,000."}]'::jsonb),

  -- G4. SBI Clerk 2026
  ('sbi-clerk-junior-associate-2026',
   'SBI Clerk 2026 — Junior Associate',
   E'SBI Junior Associate (Clerk) recruitment 2026.\n\nApprox 10,000-12,000 vacancies at SBI branches nationwide.\nOne of the highest-volume bank recruitment drives in India.\nPrelims + Mains + Local Language Test.',
   'SBI Clerk 2026 — 10,000+ vacancies. Junior Associate at SBI branches. Stable government job.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'state-bank-of-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Mumbai', 'Maharashtra', 'MH', 'India', 'IN',
   336000, 660000, 'INR', 'year', true,
   0, 0, 10000,
   now() - interval '1 day', (current_date + 25)::date,
   ARRAY['Numerical Ability','Reasoning','English','General Awareness','Computer Skills'],
   ARRAY['Bachelor degree in any discipline'],
   'Retail Banking', 'Government / BFSI',
   ARRAY['DA','HRA','Pension','Medical','Staff loan at concessional rates'],
   'external'::public.apply_mode, 'https://sbi.co.in/careers', null, null,
   '{"organization":"SBI","notification_number":"CRPD/CR/2026","notification_pdf_url":"https://sbi.co.in/clerk-2026.pdf","exam_date":"2026-09-05","age_min":20,"age_max":28,"age_relaxation":"OBC +3, SC/ST +5","fee_general":750,"fee_reserved":125,"vacancies":10000}'::jsonb,
   'active'::public.job_status, true, false, null, null, null::jsonb),

  -- G5. RBI Grade B Officer 2026
  ('rbi-grade-b-officer-2026',
   'RBI Grade B Officer 2026',
   E'Reserve Bank of India Grade B (DR) Officer recruitment 2026.\n\nPrestigious officer-grade position at India central bank.\nDepartments: Monetary Policy, Banking Supervision, Foreign Exchange.\nPhase I + Phase II + Interview.',
   'RBI Grade B 2026 — Officer at India central bank. Monetary policy, banking supervision.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'rbi'), (select user_id from pg_temp.seed_ctx limit 1),
   'Mumbai', 'Maharashtra', 'MH', 'India', 'IN',
   780000, 1500000, 'INR', 'year', true,
   0, 0, 300,
   now() - interval '4 days', (current_date + 22)::date,
   ARRAY['Economics','Finance','Quantitative Aptitude','English','Banking Regulation','Reasoning'],
   ARRAY['Bachelor degree with 60% or equivalent CGPA'],
   'Banking Regulation', 'Government / BFSI',
   ARRAY['Pension','Quarters','Medical','DA','Car loan'],
   'external'::public.apply_mode, 'https://rbi.org.in/careers', null, null,
   '{"organization":"RBI","notification_number":"RBI/DR/2026","notification_pdf_url":"https://rbi.org.in/grade-b-2026.pdf","exam_date":"2026-09-20","age_min":21,"age_max":30,"age_relaxation":"OBC +3, SC/ST +5","fee_general":850,"fee_reserved":100,"vacancies":300}'::jsonb,
   'active'::public.job_status, true, false, null, null,
   '[{"q":"What is RBI Grade B salary?","a":"Starting basic ₹35,150 + DA, HRA, and perks totaling ₹65,000-80,000/month in metro cities."},{"q":"Is there an interview?","a":"Yes — Phase I (objective), Phase II (descriptive), then Panel Interview."}]'::jsonb),

  -- G6. RRB NTPC Graduate Level 2026
  ('rrb-ntpc-graduate-level-2026',
   'RRB NTPC 2026 — Graduate Level',
   E'Railway Recruitment Board NTPC graduate-level recruitment 2026.\n\n5,810 vacancies for Station Master, Traffic Assistant, Goods Guard, Senior Clerk.\nOne of India largest railway recruitment drives.\nCBT-1 + CBT-2 + Typing/Document verification.',
   'RRB NTPC 2026 — 5,810 vacancies. Station Master, Traffic Assistant, Goods Guard posts.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'rrb'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   360000, 780000, 'INR', 'year', true,
   0, 0, 5810,
   now() - interval '5 days', (current_date + 30)::date,
   ARRAY['Mathematics','Reasoning','General Awareness','General Science','English'],
   ARRAY['Bachelor degree from recognized university'],
   'Railways', 'Government',
   ARRAY['Pension','DA','HRA','Medical','Free rail travel'],
   'external'::public.apply_mode, 'https://rrbcdg.gov.in', null, null,
   '{"organization":"RRB","notification_number":"RRB/NTPC/2026","notification_pdf_url":"https://rrbcdg.gov.in/ntpc-2026.pdf","exam_date":"2026-10-10","age_min":18,"age_max":33,"age_relaxation":"OBC +3, SC/ST +5","fee_general":500,"fee_reserved":250,"vacancies":5810}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G7. RRB Group D 2026
  ('rrb-group-d-level1-2026',
   'Railway Group D 2026 — Level 1 Posts',
   E'RRB recruitment for Track Maintainer, Helper, Porter, and other Level-1 posts.\n\nOne of the most applied-for government exams.\nPosts available in every state across Indian Railways.\nMinimum qualification: 10th pass + ITI.',
   'Railway Group D 2026 — Track Maintainer, Helper, Porter. 10th pass eligible. All India posting.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'rrb'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   216000, 420000, 'INR', 'year', true,
   0, 0, 30000,
   now() - interval '3 days', (current_date + 35)::date,
   ARRAY['Mathematics','Reasoning','General Science','General Awareness','Physical Fitness'],
   ARRAY['10th pass + ITI or equivalent'],
   'Railways', 'Government',
   ARRAY['Pension','DA','Medical','Free rail travel','Quarters'],
   'external'::public.apply_mode, 'https://rrbcdg.gov.in', null, null,
   '{"organization":"RRB","notification_number":"RRB/GD/2026","notification_pdf_url":"https://rrbcdg.gov.in/groupd-2026.pdf","exam_date":"2026-11-01","age_min":18,"age_max":33,"age_relaxation":"OBC +3, SC/ST +5","fee_general":500,"fee_reserved":250,"vacancies":30000}'::jsonb,
   'active'::public.job_status, true, true, null, null, null::jsonb),

  -- G8. RRB ALP 2026
  ('rrb-alp-assistant-loco-pilot-2026',
   'RRB ALP 2026 — Assistant Loco Pilot',
   E'Recruitment for Assistant Loco Pilot and Technician posts in Indian Railways.\n\nALP candidates undergo rigorous technical training.\nProgression to Loco Pilot operating trains across India.\nCBT-1 + CBT-2 + Computer Based Aptitude Test.',
   'RRB ALP 2026 — Assistant Loco Pilot. Technical posts in Indian Railways. ITI/Diploma eligible.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'rrb'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   300000, 660000, 'INR', 'year', true,
   0, 0, 5000,
   now() - interval '2 days', (current_date + 28)::date,
   ARRAY['Physics','Mathematics','Technical Knowledge','Electrical Basics','Mechanical Aptitude'],
   ARRAY['10th + ITI or Diploma in Engineering'],
   'Railways — Loco', 'Government',
   ARRAY['Pension','DA','Running allowance','Medical','Free rail travel'],
   'external'::public.apply_mode, 'https://rrbcdg.gov.in', null, null,
   '{"organization":"RRB","notification_number":"RRB/ALP/2026","notification_pdf_url":"https://rrbcdg.gov.in/alp-2026.pdf","exam_date":"2026-10-25","age_min":18,"age_max":30,"age_relaxation":"OBC +3, SC/ST +5","fee_general":500,"fee_reserved":250,"vacancies":5000}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G9. DRDO Scientist B 2026
  ('drdo-scientist-b-2026',
   'DRDO Scientist ''B'' 2026',
   E'Entry-level scientist positions at India premier defence research organization.\n\nWork on cutting-edge defence tech: missiles, radar, electronic warfare, advanced materials.\nRecruitment through GATE score.\nPosting at DRDO labs across India.',
   'DRDO Scientist B 2026 — Defence research. Missiles, radar, electronic warfare. GATE-based.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'drdo'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   560000, 1200000, 'INR', 'year', true,
   0, 0, 400,
   now() - interval '6 days', (current_date + 20)::date,
   ARRAY['Engineering','Research Methodology','GATE Score','Technical Writing','Problem Solving'],
   ARRAY['B.E./B.Tech with valid GATE score in ECE/ME/CS/EE'],
   'Defence R&D', 'Government / Defence',
   ARRAY['Pension','Quarters','Medical','DA','Professional allowance'],
   'external'::public.apply_mode, 'https://drdo.gov.in/careers', null, null,
   '{"organization":"DRDO","notification_number":"DRDO/RAC/2026","notification_pdf_url":"https://drdo.gov.in/scientist-b-2026.pdf","exam_date":"2026-09-01","age_min":18,"age_max":28,"age_relaxation":"OBC +3, SC/ST +5","fee_general":100,"fee_reserved":0,"vacancies":400}'::jsonb,
   'active'::public.job_status, true, false, null, null, null::jsonb),

  -- G10. Indian Army CDS 2026
  ('indian-army-cds-officer-entry-2026',
   'Indian Army Officer — CDS Entry 2026',
   E'Combined Defence Services examination for officer entry.\n\nEntry into Indian Army (IMA), Navy, Air Force, and OTA.\nRigorous training at IMA Dehradun / OTA Chennai.\nUPSC conducts the written exam + SSB interview.',
   'CDS 2026 — Officer entry into Army, Navy, Air Force. UPSC exam + SSB interview.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'indian-army'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   560000, 1400000, 'INR', 'year', true,
   0, 0, 450,
   now() - interval '4 days', (current_date + 25)::date,
   ARRAY['Physical Fitness','Leadership','General Knowledge','English','Mathematics','Strategic Thinking'],
   ARRAY['Bachelor degree (for IMA/Naval/AFA), any graduate (for OTA)'],
   'Defence — Officer', 'Government / Defence',
   ARRAY['Pension','Quarters','Medical','Canteen','Travel allowance'],
   'external'::public.apply_mode, 'https://upsconline.gov.in', null, null,
   '{"organization":"UPSC (CDS)","notification_number":"UPSC/CDS-II/2026","notification_pdf_url":"https://upsc.gov.in/cds-2026.pdf","exam_date":"2026-09-07","age_min":20,"age_max":25,"age_relaxation":"None for defence","fee_general":200,"fee_reserved":0,"vacancies":450}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G11. Indian Navy SSR 2026
  ('indian-navy-ssr-sailor-2026',
   'Indian Navy SSR 2026 — Sailor',
   E'Recruitment for Senior Secondary Recruit sailors in the Indian Navy.\n\nTraining at INS Chilka before deployment on warships.\n4-year initial engagement with option to extend.\n12th with PCM required.',
   'Navy SSR 2026 — Sailor recruitment. Training at INS Chilka. 12th PCM eligible.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'indian-navy'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   252000, 540000, 'INR', 'year', true,
   0, 0, 2500,
   now() - interval '5 days', (current_date + 30)::date,
   ARRAY['Physics','Mathematics','English','Physical Fitness','Swimming','Technical Aptitude'],
   ARRAY['12th pass with Physics, Chemistry, and Mathematics'],
   'Navy — Sailor', 'Government / Defence',
   ARRAY['Pension','Free rations','Medical','Canteen','Travel'],
   'external'::public.apply_mode, 'https://joinindiannavy.gov.in', null, null,
   '{"organization":"Indian Navy","notification_number":"Navy/SSR/2026","notification_pdf_url":"https://joinindiannavy.gov.in/ssr-2026.pdf","age_min":17,"age_max":20,"fee_general":0,"fee_reserved":0,"vacancies":2500}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G12. IAF Agniveer 2026
  ('iaf-agniveer-2026',
   'Indian Air Force Agniveer 2026',
   E'Recruitment under the Agniveer scheme for 4-year tenure in IAF.\n\nTechnical and non-technical trades.\nSkill certificate upon completion.\n25% retained as permanent cadre.',
   'IAF Agniveer 2026 — 4-year tenure. Technical and non-technical trades. 12th pass eligible.',
   'government'::public.job_category, 'contract'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'indian-air-force'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   252000, 480000, 'INR', 'year', true,
   0, 0, 3500,
   now() - interval '1 day', (current_date + 28)::date,
   ARRAY['Physics','Mathematics','English','Physical Fitness','Reasoning','Technical Aptitude'],
   ARRAY['12th pass with Physics and Mathematics for technical trades'],
   'Air Force — Agniveer', 'Government / Defence',
   ARRAY['Seva Nidhi (lump sum on exit)','Risk allowance','Ration','Medical'],
   'external'::public.apply_mode, 'https://indianairforce.nic.in', null, null,
   '{"organization":"Indian Air Force","notification_number":"IAF/AGV/2026","notification_pdf_url":"https://indianairforce.nic.in/agniveer-2026.pdf","age_min":17,"age_max":21,"fee_general":0,"fee_reserved":0,"vacancies":3500}'::jsonb,
   'active'::public.job_status, false, true, null, null, null::jsonb),

  -- G13. KVS TGT 2026
  ('kvs-tgt-trained-graduate-teacher-2026',
   'KVS TGT 2026 — Trained Graduate Teacher',
   E'Kendriya Vidyalaya Sangathan TGT recruitment 2026.\n\n3,069 vacancies across KVS schools nationwide.\nSubjects: English, Hindi, Mathematics, Science, Social Studies.\nCTET qualification mandatory.',
   'KVS TGT 2026 — 3,069 vacancies. Teaching in Kendriya Vidyalaya schools. CTET required.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'kvs'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   444000, 1140000, 'INR', 'year', true,
   0, 0, 3069,
   now() - interval '3 days', (current_date + 22)::date,
   ARRAY['Subject Expertise','Pedagogy','CTET','Classroom Management','Communication'],
   ARRAY['Bachelor degree with B.Ed + CTET Paper-II'],
   'Education', 'Government / Education',
   ARRAY['Pension','DA','HRA','Medical','Transfer across India'],
   'external'::public.apply_mode, 'https://kvsangathan.nic.in', null, null,
   '{"organization":"KVS","notification_number":"KVS/TGT/2026","notification_pdf_url":"https://kvsangathan.nic.in/tgt-2026.pdf","exam_date":"2026-10-15","age_min":21,"age_max":35,"age_relaxation":"OBC +3, SC/ST +5","fee_general":1500,"fee_reserved":0,"vacancies":3069}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G14. KVS PRT 2026
  ('kvs-prt-primary-teacher-2026',
   'KVS PRT 2026 — Primary Teacher',
   E'KVS Primary Teacher recruitment 2026.\n\n3,630 vacancies for Classes I-V.\nCentral government pay scale + housing.\n1,250+ Kendriya Vidyalaya schools across India.',
   'KVS PRT 2026 — 3,630 vacancies. Primary teacher in KV schools. CTET Paper-I required.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'kvs'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   396000, 960000, 'INR', 'year', true,
   0, 0, 3630,
   now() - interval '3 days', (current_date + 22)::date,
   ARRAY['Primary Education','Child Psychology','CTET Paper-I','Activity-Based Learning','Communication'],
   ARRAY['Graduate with D.El.Ed or B.Ed + CTET Paper-I'],
   'Education', 'Government / Education',
   ARRAY['Pension','DA','HRA','Medical','Transfer across India'],
   'external'::public.apply_mode, 'https://kvsangathan.nic.in', null, null,
   '{"organization":"KVS","notification_number":"KVS/PRT/2026","notification_pdf_url":"https://kvsangathan.nic.in/prt-2026.pdf","exam_date":"2026-10-15","age_min":21,"age_max":30,"age_relaxation":"OBC +3, SC/ST +5","fee_general":1500,"fee_reserved":0,"vacancies":3630}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G15. NVS TGT/PGT 2026
  ('nvs-teacher-tgt-pgt-2026',
   'NVS Teacher 2026 — TGT/PGT',
   E'Navodaya Vidyalaya Samiti teacher recruitment 2026.\n\n5,841 teaching and non-teaching posts.\nResidential schools in rural areas.\nFree quality education to talented rural students.',
   'NVS 2026 — 5,841 posts. TGT/PGT teachers in Navodaya residential schools across rural India.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'nvs'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   444000, 1260000, 'INR', 'year', true,
   0, 0, 5841,
   now() - interval '6 days', (current_date + 25)::date,
   ARRAY['Subject Expertise','Pedagogy','CTET','Residential School Experience','Extracurricular Skills'],
   ARRAY['Graduate/Post-graduate with B.Ed'],
   'Education', 'Government / Education',
   ARRAY['Pension','DA','Free quarters','Medical','Mess facilities'],
   'external'::public.apply_mode, 'https://navodaya.gov.in', null, null,
   '{"organization":"NVS","notification_number":"NVS/REC/2026","notification_pdf_url":"https://navodaya.gov.in/nvs-2026.pdf","exam_date":"2026-11-10","age_min":21,"age_max":40,"age_relaxation":"OBC +3, SC/ST +5","fee_general":1500,"fee_reserved":0,"vacancies":5841}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G16. NTPC GET 2026
  ('ntpc-graduate-engineer-trainee-2026',
   'NTPC Graduate Engineer Trainee 2026',
   E'NTPC recruitment for 500+ GET positions through GATE scores.\n\nIndia largest power generation company.\nComprehensive training program.\nPosting at thermal/solar power plants across India.',
   'NTPC GET 2026 — 500+ vacancies via GATE. Power generation PSU. Excellent salary and growth.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'ntpc'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   800000, 1400000, 'INR', 'year', true,
   0, 0, 500,
   now() - interval '4 days', (current_date + 20)::date,
   ARRAY['GATE Score','Engineering','Technical Knowledge','Problem Solving'],
   ARRAY['B.E./B.Tech in Electrical/Mechanical/Civil/Instrumentation with valid GATE'],
   'Power Generation', 'Government / PSU',
   ARRAY['Pension','DA','HRA','Medical','Subsidized electricity','Quarters'],
   'external'::public.apply_mode, 'https://ntpc.co.in/careers', null, null,
   '{"organization":"NTPC","notification_number":"NTPC/GET/2026","notification_pdf_url":"https://ntpc.co.in/get-2026.pdf","age_min":18,"age_max":27,"age_relaxation":"OBC +3, SC/ST +5","fee_general":300,"fee_reserved":0,"vacancies":500}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G17. ONGC Graduate Trainee 2026
  ('ongc-graduate-trainee-2026',
   'ONGC Graduate Trainee 2026',
   E'Graduate Trainee recruitment at India largest oil and gas PSU through GATE.\n\nOne of the best PSU salary packages.\nPostings across onshore/offshore exploration and production sites.\nExcellent growth trajectory.',
   'ONGC Graduate Trainee 2026 — via GATE. Oil & gas PSU. Best-in-class PSU salary package.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'ongc'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   900000, 1600000, 'INR', 'year', true,
   0, 0, 600,
   now() - interval '5 days', (current_date + 22)::date,
   ARRAY['GATE Score','Petroleum Engineering','Chemical Engineering','Mechanical Engineering','Geoscience'],
   ARRAY['B.E./B.Tech/M.Sc with valid GATE score'],
   'Exploration & Production', 'Government / PSU',
   ARRAY['Pension','DA','HRA','Medical','LTC','Performance bonus'],
   'external'::public.apply_mode, 'https://ongcindia.com/careers', null, null,
   '{"organization":"ONGC","notification_number":"ONGC/GT/2026","notification_pdf_url":"https://ongcindia.com/gt-2026.pdf","age_min":18,"age_max":28,"age_relaxation":"OBC +3, SC/ST +5","fee_general":370,"fee_reserved":0,"vacancies":600}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G18. IOCL Engineer 2026
  ('iocl-engineer-officer-2026',
   'IOCL Engineer/Officer 2026',
   E'Indian Oil Corporation recruitment for Engineers and Officers.\n\nIndia largest commercial enterprise by revenue.\nWork across refineries, pipelines, marketing terminals, and R&D centres.',
   'IOCL Engineer 2026 — via GATE. India largest oil marketing company. Refinery and pipeline posts.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'iocl'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   800000, 1400000, 'INR', 'year', true,
   0, 0, 450,
   now() - interval '6 days', (current_date + 20)::date,
   ARRAY['GATE Score','Chemical Engineering','Mechanical Engineering','Electrical Engineering'],
   ARRAY['B.E./B.Tech with valid GATE score'],
   'Refining & Pipelines', 'Government / PSU',
   ARRAY['Pension','DA','HRA','Medical','LTC','Subsidized fuel'],
   'external'::public.apply_mode, 'https://iocl.com/careers', null, null,
   '{"organization":"IOCL","notification_number":"IOCL/ENG/2026","notification_pdf_url":"https://iocl.com/engineer-2026.pdf","age_min":18,"age_max":26,"age_relaxation":"OBC +3, SC/ST +5","fee_general":300,"fee_reserved":0,"vacancies":450}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G19. BHEL Engineer Trainee 2026
  ('bhel-engineer-trainee-2026',
   'BHEL Engineer Trainee 2026',
   E'Bharat Heavy Electricals Limited Engineer Trainee recruitment.\n\nIndia largest power equipment manufacturer.\nOne year training followed by posting at manufacturing plants.\nTurbines, generators, and defence equipment.',
   'BHEL Engineer Trainee 2026 — via GATE. Power equipment manufacturing. All-India posting.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'bhel'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   700000, 1200000, 'INR', 'year', true,
   0, 0, 350,
   now() - interval '7 days', (current_date + 18)::date,
   ARRAY['GATE Score','Mechanical Engineering','Electrical Engineering','Electronics','Manufacturing'],
   ARRAY['B.E./B.Tech with valid GATE score'],
   'Manufacturing', 'Government / PSU',
   ARRAY['Pension','DA','HRA','Medical','Quarters'],
   'external'::public.apply_mode, 'https://bhel.com/careers', null, null,
   '{"organization":"BHEL","notification_number":"BHEL/ET/2026","notification_pdf_url":"https://bhel.com/et-2026.pdf","age_min":18,"age_max":27,"age_relaxation":"OBC +3, SC/ST +5","fee_general":300,"fee_reserved":0,"vacancies":350}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G20. IBPS Clerk 2026
  ('ibps-clerk-2026',
   'IBPS Clerk 2026',
   E'IBPS Clerk cadre recruitment across participating public sector banks.\n\nFront-desk operations, customer queries, account management.\nPrelims + Mains selection process.\nPosting at bank branches across India.',
   'IBPS Clerk 2026 — Bank clerk posts across PSU banks. Graduate eligible. All India posting.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'ibps'), (select user_id from pg_temp.seed_ctx limit 1),
   'Mumbai', 'Maharashtra', 'MH', 'India', 'IN',
   300000, 600000, 'INR', 'year', true,
   0, 0, 8000,
   now() - interval '2 days', (current_date + 30)::date,
   ARRAY['Numerical Ability','Reasoning','English','General Awareness','Computer Skills'],
   ARRAY['Bachelor degree in any discipline'],
   'Banking Operations', 'Government / BFSI',
   ARRAY['Pension','DA','HRA','Medical','Staff loans'],
   'external'::public.apply_mode, 'https://ibps.in', null, null,
   '{"organization":"IBPS","notification_number":"IBPS/CRP-CLERK-XVI","notification_pdf_url":"https://ibps.in/clerk-2026.pdf","exam_date":"2026-09-25","age_min":20,"age_max":28,"age_relaxation":"OBC +3, SC/ST +5","fee_general":850,"fee_reserved":175,"vacancies":8000}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G21. State PSC 2026
  ('state-psc-uppsc-mppsc-bpsc-2026',
   'State PSC 2026 — UPPSC/MPPSC/BPSC',
   E'State-level civil services examinations for SDM, DSP, BDO, and other administrative posts.\n\nState PSC exams offer governance roles at district and sub-district levels.\nSame pay structure as central services (7th Pay Commission).\nMultiple state PSCs recruiting simultaneously.',
   'State PSC 2026 — SDM, DSP, BDO posts. UP/MP/Bihar/Rajasthan. District-level governance roles.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'state-psc'), (select user_id from pg_temp.seed_ctx limit 1),
   'Lucknow', 'Uttar Pradesh', 'UP', 'India', 'IN',
   444000, 1400000, 'INR', 'year', true,
   0, 0, 3000,
   now() - interval '4 days', (current_date + 35)::date,
   ARRAY['General Studies','Current Affairs','Hindi','Ethics','Optional Subject','Interview Skills'],
   ARRAY['Bachelor degree from recognized university'],
   'State Administration', 'Government',
   ARRAY['Pension','DA','HRA','Medical','Government vehicle','Quarters'],
   'external'::public.apply_mode, 'https://uppsc.up.nic.in', null, null,
   '{"organization":"State PSC","notification_number":"UPPSC/PCS/2026","notification_pdf_url":"https://uppsc.up.nic.in/pcs-2026.pdf","exam_date":"2026-10-20","age_min":21,"age_max":40,"age_relaxation":"OBC +3, SC/ST +5","fee_general":125,"fee_reserved":65,"vacancies":3000}'::jsonb,
   'active'::public.job_status, false, false, null, null, null::jsonb),

  -- G22. CTET 2026
  ('ctet-central-teacher-eligibility-2026',
   'CTET 2026 — Central Teacher Eligibility Test',
   E'National-level eligibility test for teaching positions.\n\nMandatory for KVS, NVS, and central government schools.\nCTET qualification valid for life (2024 update).\nPaper-I (Classes 1-5) and Paper-II (Classes 6-8).',
   'CTET 2026 — Mandatory for govt teaching jobs. Lifetime validity. Paper I and II.',
   'government'::public.job_category, 'full_time'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'cbse'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   396000, 1140000, 'INR', 'year', false,
   0, 0, 100000,
   now() - interval '1 day', (current_date + 40)::date,
   ARRAY['Child Development','Pedagogy','Language','Mathematics','Environmental Studies'],
   ARRAY['D.El.Ed or B.Ed from recognized institution'],
   'Education', 'Government / Education',
   ARRAY['Opens doors to KVS/NVS/Army schools','Lifetime validity'],
   'external'::public.apply_mode, 'https://ctet.nic.in', null, null,
   '{"organization":"CBSE","notification_number":"CTET/July/2026","notification_pdf_url":"https://ctet.nic.in/2026.pdf","exam_date":"2026-12-10","age_min":18,"age_max":99,"fee_general":1000,"fee_reserved":500,"vacancies":100000}'::jsonb,
   'active'::public.job_status, false, false, null, null,
   '[{"q":"Is CTET valid for life?","a":"Yes, from 2024 onwards CTET qualification is valid for lifetime."},{"q":"Can I appear for both papers?","a":"Yes, you can appear for both Paper-I (Classes 1-5) and Paper-II (Classes 6-8) in the same attempt."}]'::jsonb)

) as v(
  slug, title, description, summary, category, job_type, work_mode,
  company_id, posted_by,
  location_city, location_state, location_state_code, location_country, location_country_code,
  salary_min, salary_max, salary_currency, salary_period, is_salary_disclosed,
  experience_min, experience_max, openings,
  posted_at, application_deadline,
  skills, qualifications, department, industry, benefits,
  apply_mode, apply_url, apply_email, apply_phone,
  government_meta, status, is_featured, is_urgent,
  meta_title, meta_description, faq
)
on conflict (slug) do nothing;

-- Verification
do $$
declare v_gov int;
begin
  select count(*) into v_gov from public.jobs where status = 'active' and category = 'government';
  raise notice 'seed_govt: active government jobs = %', v_gov;
end $$;
