-- ============================================================================
-- Seed: INTERNSHIPS (22 jobs) — July 2026
-- Requires seed_new_jobs_july2026.sql to be run first (for companies + ctx)
-- Safe to re-run: ON CONFLICT DO NOTHING on slug.
-- NOTE: Internships use category='internship', job_type='internship',
--       salary_period='month' (stipend).
-- ============================================================================

-- Resolve recruiter UUID
do $$
declare
  v_user_id uuid;
  v_override text;
begin
  begin v_override := current_setting('seed.recruiter_uuid', true);
  exception when others then v_override := null; end;
  if v_override is not null and v_override <> '' then v_user_id := v_override::uuid;
  else select id into v_user_id from auth.users order by created_at asc limit 1; end if;
  if v_user_id is null then raise exception 'Seed aborted: no posted_by UUID.'; end if;
  drop table if exists pg_temp.seed_ctx;
  create temp table pg_temp.seed_ctx (user_id uuid not null);
  insert into pg_temp.seed_ctx values (v_user_id);
end $$;

-- Internships
insert into public.jobs (
  slug, title, description, summary, category, job_type, work_mode,
  company_id, posted_by,
  location_city, location_state, location_state_code, location_country, location_country_code,
  salary_min, salary_max, salary_currency, salary_period, is_salary_disclosed,
  experience_min, experience_max, openings,
  posted_at, application_deadline,
  skills, qualifications, department, industry, benefits,
  apply_mode, apply_url, apply_email, apply_phone,
  government_meta, status, is_featured, is_urgent,
  meta_title, meta_description, faq
)
select v.*
from (values

  -- I1. SWE Intern — Google
  ('software-engineering-intern-google-bengaluru',
   'Software Engineering Intern',
   E'Google STEP/SWE internship for pre-final and final year students.\n\n**Duration:** 3 months\n**PPO chance:** 80%\n\nWork on real Google products alongside experienced engineers.\nDedicated mentor, tech talks, and potential pre-placement offer.',
   'Google SWE Intern — 3 months, ₹80K-1L/month stipend. Work on real products. High PPO chance.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'google-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   80000, 100000, 'INR', 'month', true,
   0, 0, 50,
   now() - interval '1 day', (current_date + 25)::date,
   ARRAY['Data Structures','Algorithms','Python','Java','C++','Problem Solving','System Design'],
   ARRAY['Pre-final/final year B.Tech/M.Tech in CS'],
   'Engineering', 'Technology',
   ARRAY['Free meals','Transport','Mentorship','Pre-placement offer','Swag'],
   'external'::public.apply_mode, 'https://careers.google.com/students', null, null,
   null::jsonb, 'active'::public.job_status, true, true, null, null, null::jsonb),

  -- I2. SDE Intern — Microsoft
  ('software-development-intern-microsoft-hyderabad',
   'Software Development Intern',
   E'Work on Azure, Office 365, or AI platform teams at Microsoft Hyderabad.\n\n**Duration:** 2 months\n**PPO chance:** 75%\n\nDedicated mentors, production code contributions, and full-time conversion consideration.',
   'Microsoft SDE Intern — 2 months, ₹60K-85K/month. Azure/Office 365/AI teams. Strong PPO.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'microsoft-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Hyderabad', 'Telangana', 'TG', 'India', 'IN',
   60000, 85000, 'INR', 'month', true,
   0, 0, 40,
   now() - interval '2 days', (current_date + 22)::date,
   ARRAY['C#','Python','Data Structures','Algorithms','Cloud Basics','Problem Solving'],
   ARRAY['Pre-final/final year B.Tech in CS/IT'],
   'Engineering', 'Technology',
   ARRAY['Free meals','Transport','Mentorship','Pre-placement offer','Campus housing'],
   'external'::public.apply_mode, 'https://careers.microsoft.com/students', null, null,
   null::jsonb, 'active'::public.job_status, true, false, null, null, null::jsonb),

  -- I3. SDE Intern — Amazon
  ('sde-intern-amazon-bengaluru',
   'SDE Intern',
   E'Work on Amazon retail, payments, or logistics systems.\n\n**Duration:** 2 months\n**PPO chance:** 70%\n\nOwn projects end-to-end. Performance-based pre-placement offers.',
   'Amazon SDE Intern — 2 months, ₹60K-80K/month. Retail/payments/logistics. End-to-end ownership.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'amazon-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   60000, 80000, 'INR', 'month', true,
   0, 0, 60,
   now() - interval '3 days', (current_date + 20)::date,
   ARRAY['Java','Python','Data Structures','Algorithms','OOP','Databases','AWS Basics'],
   ARRAY['Pre-final year B.Tech in CS/IT'],
   'Engineering', 'Technology',
   ARRAY['Free meals','Transport','Mentorship','Pre-placement offer'],
   'external'::public.apply_mode, 'https://amazon.jobs/students', null, null,
   null::jsonb, 'active'::public.job_status, true, false, null, null, null::jsonb),

  -- I4. Product Design Intern — Flipkart
  ('product-design-intern-flipkart-bengaluru',
   'Product Design Intern',
   E'Design user experiences for Flipkart e-commerce platform.\n\n**Duration:** 3 months\n**PPO chance:** 60%\n\nWork on real product features from discovery to implementation alongside experienced designers.',
   'Flipkart Design Intern — 3 months, ₹40K-60K/month. UX for 500M+ user e-commerce platform.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'flipkart'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   40000, 60000, 'INR', 'month', true,
   0, 0, 10,
   now() - interval '1 day', (current_date + 18)::date,
   ARRAY['Figma','UI/UX Design','User Research','Wireframing','Prototyping','Design Thinking'],
   ARRAY['Design students or fresh graduates with portfolio'],
   'Design', 'E-commerce',
   ARRAY['Free meals','Mentorship','Conversion to full-time','Learning budget'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I5. Data Science Intern — Swiggy
  ('data-science-intern-swiggy-bengaluru',
   'Data Science Intern',
   E'Work on data-driven problems in food delivery logistics.\n\n**Duration:** 4 months\n**PPO chance:** 65%\n\nApply ML models to optimize delivery routes, predict demand, and improve customer experience.',
   'Swiggy Data Science Intern — 4 months, ₹30K-50K/month. ML for logistics and demand prediction.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'swiggy'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   30000, 50000, 'INR', 'month', true,
   0, 0, 8,
   now() - interval '2 days', (current_date + 22)::date,
   ARRAY['Python','SQL','Machine Learning','Pandas','Statistics','Data Visualization','EDA'],
   ARRAY['Final year B.Tech/M.Tech or post-graduate in CS/Stats'],
   'Data Science', 'Food Tech',
   ARRAY['Free Swiggy credits','Mentorship','PPO consideration','Flexible hours'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I6. Backend Intern — Razorpay
  ('backend-development-intern-razorpay-bengaluru',
   'Backend Development Intern',
   E'Build and test microservices for Razorpay payment infrastructure.\n\n**Duration:** 3 months\n**PPO chance:** 60%\n\nWork on real payment systems handling millions of transactions.',
   'Razorpay Backend Intern — 3 months, ₹25K-45K/month. Payments microservices at scale.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'razorpay'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   25000, 45000, 'INR', 'month', true,
   0, 0, 12,
   now() - interval '4 days', (current_date + 24)::date,
   ARRAY['Go','Java','Python','REST APIs','SQL','Git','Docker Basics','Problem Solving'],
   ARRAY['Pre-final/final year B.Tech in CS/IT'],
   'Engineering', 'Fintech',
   ARRAY['Mentorship','Free meals','PPO consideration','Learning budget'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I7. AI/ML Research Intern — Adobe
  ('ai-ml-research-intern-adobe-noida',
   'AI/ML Research Intern',
   E'Conduct AI research at Adobe India Research Lab.\n\n**Duration:** 6 months\n**PPO chance:** 70%\n\nWork on generative models, computer vision, and NLP. Interns often co-author papers at top AI conferences.',
   'Adobe AI Research Intern — 6 months, ₹80K-1L/month. GenAI, CV, NLP. Publish at top venues.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'adobe-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Noida', 'Uttar Pradesh', 'UP', 'India', 'IN',
   80000, 100000, 'INR', 'month', true,
   0, 0, 15,
   now() - interval '5 days', (current_date + 20)::date,
   ARRAY['Python','Deep Learning','PyTorch','TensorFlow','Computer Vision','NLP','Research Papers'],
   ARRAY['M.Tech/PhD students in CS/AI/ML'],
   'Research', 'Technology',
   ARRAY['Research mentorship','Conference travel','Publication support','PPO'],
   'external'::public.apply_mode, 'https://research.adobe.com/careers', null, null,
   null::jsonb, 'active'::public.job_status, true, false, null, null, null::jsonb),

  -- I8. Full Stack Intern — Infosys InStep
  ('full-stack-intern-infosys-instep-bengaluru',
   'Full Stack Development Intern — InStep',
   E'Infosys InStep global internship program.\n\n**Duration:** 3 months\n**PPO chance:** 50%\n\nHands-on experience building enterprise applications with cutting-edge technologies.',
   'Infosys InStep Intern — 3 months, ₹25K-50K/month. Enterprise full-stack development.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'infosys'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   25000, 50000, 'INR', 'month', true,
   0, 0, 30,
   now() - interval '3 days', (current_date + 28)::date,
   ARRAY['React','Node.js','JavaScript','HTML/CSS','MongoDB','Git','REST APIs','Agile'],
   ARRAY['Pre-final/final year B.Tech in CS/IT'],
   'Engineering', 'IT Services',
   ARRAY['Certificate','Mentorship','Campus housing','Pre-placement offer'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I9. Marketing Intern — Meesho
  ('marketing-intern-meesho-bengaluru',
   'Marketing Intern',
   E'Support Meesho growth marketing team with campaigns and analytics.\n\n**Duration:** 3 months\n**PPO chance:** 40%\n\nGet hands-on experience in growth hacking for a hyper-growth social commerce startup.',
   'Meesho Marketing Intern — 3 months, ₹15K-25K/month. Growth marketing, social media, campaigns.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'meesho'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   15000, 25000, 'INR', 'month', true,
   0, 0, 8,
   now() - interval '1 day', (current_date + 20)::date,
   ARRAY['Digital Marketing','Social Media','Content Creation','Analytics','Canva','SEO Basics'],
   ARRAY['Any year student — marketing or communications preferred'],
   'Marketing', 'E-commerce',
   ARRAY['Certificate','Mentorship','Flexible hours','Meesho credits'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I10. Finance Intern — Goldman Sachs
  ('finance-intern-goldman-sachs-bengaluru',
   'Finance Intern — Summer Analyst',
   E'Summer analyst internship at Goldman Sachs.\n\n**Duration:** 2 months\n**PPO chance:** 85%\n\nWork on live deals, market analysis, and risk assessment. Top-tier compensation.',
   'Goldman Sachs Summer Analyst — 2 months, ₹50K-75K/month. Live deals, market analysis.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'goldman-sachs-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   50000, 75000, 'INR', 'month', true,
   0, 0, 20,
   now() - interval '6 days', (current_date + 18)::date,
   ARRAY['Financial Analysis','Excel','Accounting','Valuation','Financial Modeling','Communication'],
   ARRAY['Pre-final year MBA/finance/CA students'],
   'Investment Banking', 'BFSI',
   ARRAY['Top-tier compensation','Mentorship','Networking events','PPO'],
   'external'::public.apply_mode, 'https://goldmansachs.com/careers', null, null,
   null::jsonb, 'active'::public.job_status, true, false, null, null, null::jsonb),

  -- I11. Content Writing Intern — Zomato
  ('content-writing-intern-zomato-remote',
   'Content Writing Intern',
   E'Create engaging food and restaurant content for Zomato.\n\n**Duration:** 3 months\n**PPO chance:** 30%\n\nWrite restaurant reviews, city food guides, and marketing copy. Fully remote.',
   'Zomato Content Intern — 3 months, ₹10K-20K/month. Food writing, SEO content. Remote.',
   'internship'::public.job_category, 'internship'::public.job_type, 'remote'::public.work_mode,
   (select id from public.companies where slug = 'zomato'), (select user_id from pg_temp.seed_ctx limit 1),
   null, null, null, 'India', 'IN',
   10000, 20000, 'INR', 'month', true,
   0, 0, 15,
   now() - interval '2 days', (current_date + 25)::date,
   ARRAY['Creative Writing','SEO Writing','Social Media','Research','Grammar','Content Strategy'],
   ARRAY['Any year student — English/journalism/communications preferred'],
   'Content', 'Food Tech',
   ARRAY['Remote work','Zomato credits','Certificate','Portfolio building'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I12. DevOps Intern — PhonePe
  ('devops-intern-phonepe-bengaluru',
   'DevOps Intern',
   E'Learn and implement DevOps practices for PhonePe infrastructure.\n\n**Duration:** 4 months\n**PPO chance:** 55%\n\nHands-on with cloud infrastructure, monitoring, and deployment automation at massive scale.',
   'PhonePe DevOps Intern — 4 months, ₹25K-40K/month. Cloud, CI/CD, monitoring at scale.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'phonepe'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   25000, 40000, 'INR', 'month', true,
   0, 0, 6,
   now() - interval '4 days', (current_date + 22)::date,
   ARRAY['Linux','Docker','AWS','Python','CI/CD','Git','Networking Basics','Scripting'],
   ARRAY['Pre-final/final year B.Tech in CS/IT'],
   'Platform Engineering', 'Fintech',
   ARRAY['Mentorship','Free meals','PPO consideration','Learning budget'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I13. Graphic Design Intern — Nykaa
  ('graphic-design-intern-nykaa-mumbai',
   'Graphic Design Intern',
   E'Create visual content for Nykaa beauty and fashion brand.\n\n**Duration:** 3 months\n**PPO chance:** 35%\n\nWork on social media, website banners, and email campaigns for seasonal launches.',
   'Nykaa Design Intern — 3 months, ₹10K-18K/month. Beauty brand visuals, social media design.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'nykaa'), (select user_id from pg_temp.seed_ctx limit 1),
   'Mumbai', 'Maharashtra', 'MH', 'India', 'IN',
   10000, 18000, 'INR', 'month', true,
   0, 0, 5,
   now() - interval '1 day', (current_date + 20)::date,
   ARRAY['Adobe Photoshop','Illustrator','Canva','Social Media Design','Typography','Color Theory'],
   ARRAY['Design students — any year'],
   'Creative', 'E-commerce',
   ARRAY['Nykaa products','Certificate','Portfolio building','Mentorship'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I14. ML Intern — Jio
  ('machine-learning-intern-jio-hyderabad',
   'Machine Learning Intern',
   E'Work on ML projects for Jio telecom and digital services.\n\n**Duration:** 6 months\n**PPO chance:** 50%\n\nBuild models for network optimization, customer analytics, and AI-powered services.',
   'Jio ML Intern — 6 months, ₹20K-35K/month. Telecom ML models, network optimization.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'jio-platforms'), (select user_id from pg_temp.seed_ctx limit 1),
   'Hyderabad', 'Telangana', 'TG', 'India', 'IN',
   20000, 35000, 'INR', 'month', true,
   0, 0, 10,
   now() - interval '5 days', (current_date + 25)::date,
   ARRAY['Python','TensorFlow','PyTorch','Machine Learning','NLP','NumPy','Pandas','Scikit-learn'],
   ARRAY['M.Tech/final year B.Tech in CS/AI/ML'],
   'AI Centre', 'Telecom',
   ARRAY['Mentorship','Certificate','Jio benefits','PPO consideration'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I15. HR Intern — Tata Group
  ('hr-intern-tata-group-mumbai',
   'HR Intern',
   E'Support HR team with recruitment and employee engagement.\n\n**Duration:** 2 months\n**PPO chance:** 40%\n\nGain HR ops experience at one of India largest and most respected conglomerates.',
   'Tata Group HR Intern — 2 months, ₹12K-20K/month. Recruitment, onboarding, engagement.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'tata-group'), (select user_id from pg_temp.seed_ctx limit 1),
   'Mumbai', 'Maharashtra', 'MH', 'India', 'IN',
   12000, 20000, 'INR', 'month', true,
   0, 0, 10,
   now() - interval '3 days', (current_date + 22)::date,
   ARRAY['HR Basics','Communication','Excel','Recruitment','Employee Engagement','Presentation'],
   ARRAY['MBA HR students — any year'],
   'Human Resources', 'Conglomerate',
   ARRAY['Certificate','Tata brand on CV','Mentorship','Networking'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I16. Cybersecurity Intern — Wipro
  ('cybersecurity-intern-wipro-hyderabad',
   'Cybersecurity Intern',
   E'Assist the cybersecurity team with threat monitoring and security audits.\n\n**Duration:** 3 months\n**PPO chance:** 45%\n\nLearn enterprise security practices on real client projects.',
   'Wipro Cybersecurity Intern — 3 months, ₹15K-25K/month. Threat monitoring, security audits.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'wipro'), (select user_id from pg_temp.seed_ctx limit 1),
   'Hyderabad', 'Telangana', 'TG', 'India', 'IN',
   15000, 25000, 'INR', 'month', true,
   0, 0, 8,
   now() - interval '2 days', (current_date + 24)::date,
   ARRAY['Network Security','SIEM Basics','Linux','Python','Vulnerability Assessment','OWASP'],
   ARRAY['CS/IT students — pre-final/final year'],
   'Cybersecurity', 'IT Services',
   ARRAY['Certificate','Training','Mentorship','PPO consideration'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I17. Business Development Intern — Groww
  ('business-development-intern-groww-bengaluru',
   'Business Development Intern',
   E'Drive user acquisition and partnership initiatives for Groww.\n\n**Duration:** 3 months\n**PPO chance:** 40%\n\nConduct market research, identify growth opportunities, and support B2B partnerships.',
   'Groww BD Intern — 3 months, ₹15K-25K/month. Fintech partnerships, market research.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'groww'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   15000, 25000, 'INR', 'month', true,
   0, 0, 6,
   now() - interval '1 day', (current_date + 20)::date,
   ARRAY['Communication','Sales','Market Research','Excel','CRM Tools','Presentation'],
   ARRAY['MBA/BBA students — any year'],
   'Business Development', 'Fintech',
   ARRAY['Certificate','Groww credits','Mentorship','Flexible hours'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I18. Frontend Intern — CRED
  ('frontend-development-intern-cred-bengaluru',
   'Frontend Development Intern',
   E'Build beautiful UI components for CRED fintech app.\n\n**Duration:** 3 months\n**PPO chance:** 60%\n\nWork in a design-first engineering culture known for exceptional UI quality.',
   'CRED Frontend Intern — 3 months, ₹30K-50K/month. Premium fintech UI, React, design-first.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'cred'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   30000, 50000, 'INR', 'month', true,
   0, 0, 8,
   now() - interval '2 days', (current_date + 18)::date,
   ARRAY['React','JavaScript','TypeScript','HTML/CSS','Git','Responsive Design','API Integration'],
   ARRAY['Pre-final/final year B.Tech in CS/IT'],
   'Frontend Engineering', 'Fintech',
   ARRAY['Free meals','Mentorship','PPO consideration','Learning budget'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, true, null, null, null::jsonb),

  -- I19. Supply Chain Intern — Amazon
  ('supply-chain-operations-intern-amazon-delhi',
   'Supply Chain & Operations Intern',
   E'Support Amazon fulfilment centre operations.\n\n**Duration:** 2 months\n**PPO chance:** 65%\n\nProcess improvement, data analysis, and logistics optimization at massive scale.',
   'Amazon Ops Intern — 2 months, ₹20K-35K/month. Fulfilment centre, supply chain analytics.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'amazon-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'New Delhi', 'Delhi', 'DL', 'India', 'IN',
   20000, 35000, 'INR', 'month', true,
   0, 0, 15,
   now() - interval '4 days', (current_date + 22)::date,
   ARRAY['Excel','Data Analysis','Supply Chain Basics','Communication','Problem Solving','SQL Basics'],
   ARRAY['MBA/engineering students — any year'],
   'Operations', 'E-commerce',
   ARRAY['Certificate','Amazon credits','Mentorship','PPO consideration'],
   'external'::public.apply_mode, 'https://amazon.jobs/students', null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I20. Social Media Intern — Dunzo (Remote)
  ('social-media-marketing-intern-dunzo-remote',
   'Social Media Marketing Intern',
   E'Manage social media presence and create content for Dunzo.\n\n**Duration:** 3 months\n**PPO chance:** 25%\n\nPlan social media calendars, create memes/reels, track engagement. Fully remote.',
   'Dunzo Social Media Intern — 3 months, ₹8K-15K/month. Content creation, memes, reels. Remote.',
   'internship'::public.job_category, 'internship'::public.job_type, 'remote'::public.work_mode,
   (select id from public.companies where slug = 'dunzo'), (select user_id from pg_temp.seed_ctx limit 1),
   null, null, null, 'India', 'IN',
   8000, 15000, 'INR', 'month', true,
   0, 0, 5,
   now() - interval '1 day', (current_date + 18)::date,
   ARRAY['Social Media Management','Content Creation','Instagram','Twitter','Analytics','Canva'],
   ARRAY['Any year student — marketing/communications preferred'],
   'Marketing', 'Quick Commerce',
   ARRAY['Remote work','Certificate','Dunzo credits','Portfolio building'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I21. Data Analytics Intern — Deloitte
  ('data-analytics-intern-deloitte-mumbai',
   'Data Analytics Intern',
   E'Work on consulting analytics projects for enterprise clients.\n\n**Duration:** 3 months\n**PPO chance:** 60%\n\nBuild dashboards, perform data analysis, and present insights to client stakeholders.',
   'Deloitte Analytics Intern — 3 months, ₹25K-40K/month. Consulting analytics, Power BI, SQL.',
   'internship'::public.job_category, 'internship'::public.job_type, 'hybrid'::public.work_mode,
   (select id from public.companies where slug = 'deloitte-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Mumbai', 'Maharashtra', 'MH', 'India', 'IN',
   25000, 40000, 'INR', 'month', true,
   0, 0, 12,
   now() - interval '5 days', (current_date + 20)::date,
   ARRAY['SQL','Python','Excel','Power BI','Tableau','Statistics','Data Cleaning','Presentation'],
   ARRAY['Final year B.Tech/MBA/M.Sc in analytics/stats'],
   'Consulting', 'Consulting',
   ARRAY['Certificate','Deloitte brand on CV','Mentorship','PPO consideration'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb),

  -- I22. Embedded Systems Intern — Bosch
  ('embedded-systems-intern-bosch-bengaluru',
   'Embedded Systems Intern',
   E'Work on automotive and IoT embedded systems projects.\n\n**Duration:** 6 months\n**PPO chance:** 55%\n\nHands-on with real-time systems, sensor integration, and automotive-grade software at Bosch R&D.',
   'Bosch Embedded Intern — 6 months, ₹20K-35K/month. Automotive IoT, RTOS, microcontrollers.',
   'internship'::public.job_category, 'internship'::public.job_type, 'onsite'::public.work_mode,
   (select id from public.companies where slug = 'bosch-india'), (select user_id from pg_temp.seed_ctx limit 1),
   'Bengaluru', 'Karnataka', 'KA', 'India', 'IN',
   20000, 35000, 'INR', 'month', true,
   0, 0, 10,
   now() - interval '3 days', (current_date + 25)::date,
   ARRAY['C/C++','Embedded C','Microcontrollers','RTOS','IoT','PCB Design','Serial Protocols'],
   ARRAY['ECE/EEE final year B.Tech students'],
   'R&D', 'Manufacturing',
   ARRAY['Certificate','Bosch brand on CV','Mentorship','PPO consideration','Canteen'],
   'internal'::public.apply_mode, null, null, null,
   null::jsonb, 'active'::public.job_status, false, false, null, null, null::jsonb)

) as v(
  slug, title, description, summary, category, job_type, work_mode,
  company_id, posted_by,
  location_city, location_state, location_state_code, location_country, location_country_code,
  salary_min, salary_max, salary_currency, salary_period, is_salary_disclosed,
  experience_min, experience_max, openings,
  posted_at, application_deadline,
  skills, qualifications, department, industry, benefits,
  apply_mode, apply_url, apply_email, apply_phone,
  government_meta, status, is_featured, is_urgent,
  meta_title, meta_description, faq
)
on conflict (slug) do nothing;

-- Verification
do $$
declare v_intern int;
begin
  select count(*) into v_intern from public.jobs where status = 'active' and category = 'internship';
  raise notice 'seed_internships: active internships = %', v_intern;
end $$;
